# Generated by Django 4.2.11 on 2024-03-19 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("publications", "0038_issn_eissn_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "importance",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "Normal"), (20, "Important")], default=10
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General announcements"),
                            ("overlap", "Overlap"),
                            ("platform", "Platform info"),
                            ("sushi", "SUSHI"),
                            ("tags", "Tags"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publications.platform",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "handling",
                    models.CharField(
                        choices=[
                            ("ignore", "Ignore"),
                            ("notify", "Notify in app"),
                            ("email", "Email"),
                        ],
                        max_length=10,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                (
                    "first_read_date",
                    models.DateTimeField(
                        blank=True, help_text="First time the user read the event", null=True
                    ),
                ),
                (
                    "email_sent_date",
                    models.DateTimeField(
                        blank=True, help_text="Used when publishing the event via email", null=True
                    ),
                ),
                (
                    "notification_sent_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Used when publishing the event through the API",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "error_log",
                    models.TextField(
                        blank=True, help_text="Error log if sending email or notification failed"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={"unique_together": {("user", "event")}},
        ),
        migrations.AddField(
            model_name="event",
            name="users",
            field=models.ManyToManyField(
                related_name="assigned_events",
                through="events.UserEvent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserEventCategoryHandling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General announcements"),
                            ("overlap", "Overlap"),
                            ("platform", "Platform info"),
                            ("sushi", "SUSHI"),
                            ("tags", "Tags"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "importance",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "Normal"), (20, "Important")], default=10
                    ),
                ),
                (
                    "handling_method",
                    models.CharField(
                        choices=[
                            ("ignore", "Ignore"),
                            ("notify", "Notify in app"),
                            ("email", "Email"),
                        ],
                        default="notify",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={"unique_together": {("user", "category", "importance")}},
        ),
    ]
