# Generated by Django 4.2.11 on 2024-04-22 14:24

"""
Creates a new Event informing about the introduction of events and connects it to all existing users
"""

from datetime import timedelta

from django.db import migrations
from django.utils.timezone import now


def create_initial_info_event(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    User = apps.get_model("core", "User")
    UserEvent = apps.get_model("events", "UserEvent")

    event = Event.objects.create(
        title="Introducing events",
        description="In CELUS 6.0.0 we are introducing 'Events' - a new way to let you know about "
        "what's happening in CELUS. For now, events are used to inform about broken credentials, "
        "finished manual harvests, finished title list imports, and more. \n\nIn future, we will "
        "introduce more types of events and more ways to interact with them. Stay tuned!",
        expiration_date=now() + timedelta(days=90),
        importance=10,
        category="general",
    )

    ues = []
    for user in User.objects.all():
        ues.append(UserEvent(user=user, event=event, handling="notify"))
    UserEvent.objects.bulk_create(ues)


def remove_initial_info_event(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Event.objects.filter(title="Introducing events").delete()


class Migration(migrations.Migration):
    dependencies = [("events", "0002_alter_event_last_updated_by")]

    operations = [migrations.RunPython(create_initial_info_event, remove_initial_info_event)]
