# Generated by Django 2.2.4 on 2019-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('sushi', '0003_counterreporttype_active')]

    operations = [
        migrations.AddField(
            model_name='sushifetchattempt',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Was the data converted into logs?'),
        ),
        migrations.AddField(
            model_name='sushifetchattempt',
            name='when_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
