# Generated by Django 2.2.4 on 2019-08-16 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('sushi', '0007_sushifetchattempt_import_batch')]

    operations = [
        migrations.AlterField(
            model_name='sushifetchattempt',
            name='import_batch',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='logs.ImportBatch'
            ),
        )
    ]
