# Generated by Django 2.2.4 on 2019-08-25 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0008_sushiattemp_importbatch_onetoone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterreporttype',
            name='report_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logs.ReportType'),
        ),
    ]
