# Generated by Django 2.2.4 on 2019-08-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0009_conterreporttype_oneonone_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterreporttype',
            name='code',
            field=models.CharField(
                choices=[
                    ('JR1', 'JR1'),
                    ('JR1a', 'JR1a'),
                    ('JR1GOA', 'JR1GOA'),
                    ('JR2', 'JR2'),
                    ('JR5', 'JR5'),
                    ('BR1', 'BR1'),
                    ('BR2', 'BR2'),
                    ('BR3', 'BR3'),
                    ('DB1', 'DB1'),
                    ('DB2', 'DB2'),
                    ('PR1', 'PR1'),
                    ('TR', 'TR'),
                    ('PR', 'PR'),
                    ('DR', 'DR'),
                ],
                max_length=10,
            ),
        ),
    ]
