# Generated by Django 2.2.4 on 2019-08-29 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0012_sushifetchattempt_contains_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sushifetchattempt',
            old_name='success',
            new_name='download_success',
        ),
        migrations.AddField(
            model_name='sushifetchattempt',
            name='queue_previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='queue_following', to='sushi.SushiFetchAttempt'),
        ),
    ]
