# Generated by Django 2.2.4 on 2019-09-13 08:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0016_counterreporttype_superseeded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sushifetchattempt',
            name='processing_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Internal info'),
        ),
    ]
