# Generated by Django 2.2.5 on 2019-09-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0017_sushifetchattempt_processing_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sushifetchattempt',
            name='in_progress',
            field=models.BooleanField(
                default=False, help_text='True if the data is still downloading'
            ),
        ),
    ]
