# Generated by Django 2.2.5 on 2019-09-16 13:36

from django.db import migrations, models
import sushi.models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0018_sushifetchattempt_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sushifetchattempt',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to=sushi.models.where_to_store),
        ),
        migrations.AlterField(
            model_name='sushifetchattempt',
            name='download_success',
            field=models.BooleanField(default=False, help_text='True if there was no error downloading data'),
        ),
        migrations.AlterField(
            model_name='sushifetchattempt',
            name='processing_success',
            field=models.BooleanField(default=False, help_text='True if there was no error extracting data from the downloaded material'),
        ),
    ]
