# Generated by Django 2.2.5 on 2019-11-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0024_lock_level_change'),
    ]

    operations = [
        migrations.RemoveField(model_name='counterreporttype', name='superseeded_by',),
    ]
