# Generated by Django 2.2.5 on 2019-11-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    # dependency on 0028_reporttype_superseeded_by was added ex-post when I found out that
    # in some cases the migration order was incorrect and this change occurred before
    # 0028_reporttype_superseeded_by which is incorrect
    dependencies = [('sushi', '0024_lock_level_change'), ('logs', '0028_reporttype_superseeded_by')]

    operations = [migrations.RemoveField(model_name='counterreporttype', name='superseeded_by')]
