# Generated by Django 2.2.14 on 2020-08-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0030_sushicredentials_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sushifetchattempt',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
