# Generated by Django 2.2.15 on 2020-09-01 07:56

from datetime import timedelta
from django.db import migrations
from django.db.models import F
from django.utils.timezone import now


def mark_older_3030_as_unqueued(apps, schema_editor):
    """Removes queued flag from some fetchattempts
    The attempts are supposed to have 3030 code and have distant end_data
    """
    SushiFetchAttempt = apps.get_model('sushi', 'SushiFetchAttempt')
    SushiFetchAttempt.objects.filter(error_code="3030").exclude(
        end_date__gt=F('timestamp') - timedelta(days=45)
    ).update(queued=False, is_processed=True, when_processed=now())


class Migration(migrations.Migration):

    dependencies = [('sushi', '0031_sushifetchattempt_last_updated')]

    operations = [migrations.RunPython(mark_older_3030_as_unqueued)]
