# Generated by Django 2.2.15 on 2020-09-07 17:38

import sushi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('sushi', '0033_sushifetchattempt_queue_id')]

    operations = [
        migrations.AlterField(
            model_name='sushifetchattempt',
            name='data_file',
            field=models.FileField(
                blank=True, max_length=256, null=True, upload_to=sushi.models.where_to_store
            ),
        )
    ]
