# Generated by Django 2.2.15 on 2020-10-01 10:59

from django.db import migrations, models


def active_couter_reports_to_counter_reports(apps, schema_editor):
    CounterReportsToCredentials = apps.get_model('sushi', 'CounterReportsToCredentials')
    SushiCredentials = apps.get_model('sushi', 'SushiCredentials')
    for credentials in SushiCredentials.objects.all():
        for counter_report in credentials.active_counter_reports.all():
            CounterReportsToCredentials.objects.create(
                credentials=credentials, counter_report=counter_report
            )


def couter_reports_to_active_counter_reports(apps, schema_editor):
    CounterReportsToCredentials = apps.get_model('sushi', 'CounterReportsToCredentials')
    for cr2c in CounterReportsToCredentials.objects.all():
        cr2c.credentials.active_counter_reports.add(cr2c.counter_report)


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0035_sushifetchattempt_http_status_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterReportsToCredentials',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'credentials',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE, to='sushi.SushiCredentials'
                    ),
                ),
                (
                    'counter_report',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE, to='sushi.CounterReportType'
                    ),
                ),
            ],
            options={'unique_together': {('credentials', 'counter_report')}},
        ),
        migrations.AddField(
            model_name='sushicredentials',
            name='counter_reports',
            field=models.ManyToManyField(
                through='sushi.CounterReportsToCredentials',
                to='sushi.CounterReportType',
                related_name='sushicredentials_set',
            ),
        ),
        migrations.RunPython(
            active_couter_reports_to_counter_reports, couter_reports_to_active_counter_reports
        ),
        migrations.RemoveField(model_name='sushicredentials', name='active_counter_reports',),
    ]
