# Generated by Django 3.1.3 on 2020-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('sushi', '0037_broken_credentials')]

    operations = [
        migrations.AlterField(
            model_name='sushicredentials',
            name='extra_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sushifetchattempt',
            name='processing_info',
            field=models.JSONField(default=dict, help_text='Internal info'),
        ),
    ]
