# Generated by Django 3.1.6 on 2021-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0040_broken_blank_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterreporttype',
            name='code',
            field=models.CharField(
                choices=[
                    ('JR1', 'JR1'),
                    ('JR1a', 'JR1a'),
                    ('JR1GOA', 'JR1GOA'),
                    ('JR2', 'JR2'),
                    ('BR1', 'BR1'),
                    ('BR2', 'BR2'),
                    ('BR3', 'BR3'),
                    ('DB1', 'DB1'),
                    ('DB2', 'DB2'),
                    ('PR1', 'PR1'),
                    ('MR1', 'MR1'),
                    ('TR', 'TR'),
                    ('PR', 'PR'),
                    ('DR', 'DR'),
                    ('IR', 'IR'),
                    ('TR', 'TR'),
                    ('PR', 'PR'),
                    ('DR', 'DR'),
                    ('IR', 'IR'),
                ],
                max_length=10,
            ),
        ),
    ]
