# Generated by Django 3.1.13 on 2021-09-20 11:22

from django.db import migrations
from datetime import date


def add_fetch_intention(apps, schema_editor):
    SushiFetchAttempt = apps.get_model('sushi', 'SushiFetchAttempt')
    Harvest = apps.get_model('scheduler', 'Harvest')
    FetchIntention = apps.get_model('scheduler', 'FetchIntention')

    datestamp = date(2020, 1, 1)
    organization_id = None
    harvest = None

    for attempt in (
        SushiFetchAttempt.objects.filter(fetchintention__isnull=True)
        .order_by('credentials__organization', 'timestamp')
        .select_related('credentials')
        .iterator()
    ):

        # group intentions per organization per day
        this_date = attempt.timestamp.date()
        if organization_id != attempt.credentials.organization_id or datestamp != this_date:
            harvest = Harvest.objects.create()
            organization_id = attempt.credentials.organization_id
            datestamp = this_date

        FetchIntention.objects.create(
            harvest=harvest,
            not_before=attempt.timestamp,
            credentials_id=attempt.credentials_id,
            counter_report_id=attempt.counter_report_id,
            scheduler=None,
            start_date=attempt.start_date,
            end_date=attempt.end_date,
            when_processed=attempt.timestamp,
            attempt=attempt,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0045_fetchattempt_statemachine'),
    ]

    operations = [
        migrations.RunPython(add_fetch_intention, migrations.RunPython.noop),
    ]
