# Generated by Django 3.2.9 on 2021-11-26 15:34

from django.db import migrations, models


def update_no_data(apps, schema_editor):
    SushiFetchAttempt = apps.get_model('sushi', 'SushiFetchAttempt')
    SushiFetchAttempt.objects.filter(error_code__in=['3030', '3031']).update(status="no_data")


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0046_fetchintentions_for_fetch_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sushifetchattempt',
            name='status',
            field=models.CharField(
                choices=[
                    ('initial', 'Initial'),
                    ('downloading', 'Downloading'),
                    ('importing', 'Importing'),
                    ('success', 'Success'),
                    ('unprocessed', 'Unprocessed'),
                    ('no_data', 'No data'),
                    ('import_failed', 'Import failed'),
                    ('parsing_failed', 'Parsing failed'),
                    ('download_failed', 'Download failed'),
                    ('credentails_broken', 'Broken credentials'),
                    ('canceled', 'Canceled'),
                ],
                default='initial',
                max_length=20,
            ),
        ),
        migrations.RunPython(update_no_data, migrations.RunPython.noop),
    ]
