# Generated by Django 3.2.12 on 2022-02-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('sushi', '0048_discard_credentials_broken_state')]

    operations = [
        migrations.AddField(
            model_name='sushifetchattempt',
            name='extracted_data',
            field=models.JSONField(
                default=dict, help_text='Information extracted from the SUSHI data header'
            ),
        )
    ]
