# Generated by Django 3.2.12 on 2022-04-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0050_alter_sushicredentials_api_key'),
    ]

    operations = [
        migrations.RemoveField(model_name='sushifetchattempt', name='queue_id'),
        migrations.RemoveField(model_name='sushifetchattempt', name='queue_previous'),
        migrations.RemoveField(model_name='sushifetchattempt', name='when_queued'),
    ]
