# Generated by Django 3.2.16 on 2022-12-07 11:51

from django.db import migrations

from sushi.logic.cleanup import fetch_attempt_fill_in_missing_header_data


def fill_missing_extracted_data(apps, schema_editor):
    fetch_attempt_fill_in_missing_header_data()


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0054_file_checksums'),
    ]

    operations = [
        migrations.RunPython(fill_missing_extracted_data, migrations.RunPython.noop),
    ]
