# Generated by Django 3.2.16 on 2022-12-07 11:51
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def fill_missing_extracted_data(apps, schema_editor):
    SushiFetchAttempt = apps.get_model("sushi", "SushiFetchAttempt")
    attempts = SushiFetchAttempt.objects.filter(
        extracted_data={}, counter_report__counter_version=5, data_file__isnull=False
    )
    if attempts.count():
        logger.warning(
            'Found %d fetch attempts which are potentially missing extracted data. '
            'You should run `python manage.py reextract_fa_headers`',
            attempts.count(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0054_file_checksums'),
    ]

    operations = [
        migrations.RunPython(fill_missing_extracted_data, migrations.RunPython.noop),
    ]
