# Generated by Django 3.2.18 on 2023-05-03 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0055_fill_missing_extracted_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sushifetchattempt',
            name='credentials',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='sushi.sushicredentials'
            ),
        ),
    ]
