# Generated by Django 3.2.19 on 2023-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sushi', '0057_alter_sushifetchattempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterreportstocredentials',
            name='broken',
            field=models.CharField(
                blank=True,
                choices=[('http', 'HTTP'), ('sushi', 'SUSHI')],
                help_text='Indication that credentials are broken',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='sushicredentials',
            name='broken',
            field=models.CharField(
                blank=True,
                choices=[('http', 'HTTP'), ('sushi', 'SUSHI')],
                help_text='Indication that credentials are broken',
                max_length=20,
                null=True,
            ),
        ),
    ]
