# Generated by Django 4.2.11 on 2024-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sushi", "0060_alter_sushicredentials_last_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="sushicredentials",
            name="auto_update_url",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sushicredentials",
            name="forced_verified_hash",
            field=models.CharField(
                blank=True,
                help_text="Force verified=True for given hash - "
                "useful to preserve verification when URL is automatically updated",
                max_length=32,
            ),
        ),
    ]
