# Generated by Django 4.2.13 on 2024-06-26 12:44

import django.db.models.deletion
from django.db import migrations, models


def mark_clashing_attempts(apps, schema_editor):
    SushiFetchAttempt = apps.get_model("sushi", "SushiFetchAttempt")
    ImportBatch = apps.get_model("logs", "ImportBatch")
    for attempt in SushiFetchAttempt.objects.filter(
        status="import_failed", log__icontains="clashing import batch", credentials__isnull=False
    ).select_related("credentials", "counter_report"):
        try:
            attempt.clashing_import_batch = ImportBatch.objects.get(
                organization_id=attempt.credentials.organization_id,
                platform_id=attempt.credentials.platform_id,
                report_type=attempt.counter_report.report_type,
                date=attempt.start_date,
            )
            attempt.save()
        except ImportBatch.DoesNotExist:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0083_alter_importbatchsynclog_last_updated_by_and_more"),
        ("sushi", "0061_sushicredentials_auto_update_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sushifetchattempt",
            name="clashing_import_batch",
            field=models.ForeignKey(
                blank=True,
                help_text="If the attempt cannot be imported because of a clashing import batch, "
                "this field will contain the clashing import batch",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clashing_attempts",
                to="logs.importbatch",
            ),
        ),
        # find all attempts with clashing import batches and store them in the new field
        migrations.RunPython(mark_clashing_attempts, reverse_code=migrations.RunPython.noop),
    ]
