# Generated by Django 4.2.11 on 2024-04-22 12:56
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sushi", "0062_sushifetchattempt_clashing_import_batch")]

    operations = [
        migrations.AlterField(
            model_name="counterreporttype",
            name="code",
            field=models.CharField(
                choices=[
                    ("JR1", "JR1"),
                    ("JR1a", "JR1a"),
                    ("JR1GOA", "JR1GOA"),
                    ("JR2", "JR2"),
                    ("BR1", "BR1"),
                    ("BR2", "BR2"),
                    ("BR3", "BR3"),
                    ("DB1", "DB1"),
                    ("DB2", "DB2"),
                    ("PR1", "PR1"),
                    ("MR1", "MR1"),
                    ("TR", "TR"),
                    ("PR", "PR"),
                    ("DR", "DR"),
                    ("IR", "IR"),
                    ("IR_M1", "IR_M1"),
                ],
                max_length=10,
            ),
        )
    ]
