# Generated by Django 4.2.14 on 2024-07-29 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sushi", "0063_alter_counterreporttype_code")]

    operations = [
        migrations.AddField(
            model_name="sushifetchattempt",
            name="used_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Url used for sushi harvesting",
                validators=[django.core.validators.URLValidator()],
            ),
        )
    ]
