# Generated by Django 4.2.16 on 2024-11-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sushi", "0064_sushifetchattempt_sushi_url")]

    operations = [
        migrations.AlterField(
            model_name="counterreporttype",
            name="code",
            field=models.CharField(
                choices=[
                    ("JR1", "JR1"),
                    ("JR1a", "JR1a"),
                    ("JR1GOA", "JR1GOA"),
                    ("JR2", "JR2"),
                    ("BR1", "BR1"),
                    ("BR2", "BR2"),
                    ("BR3", "BR3"),
                    ("DB1", "DB1"),
                    ("DB2", "DB2"),
                    ("PR1", "PR1"),
                    ("MR1", "MR1"),
                    ("TR", "TR"),
                    ("PR", "PR"),
                    ("DR", "DR"),
                    ("IR_M1", "IR_M1"),
                    ("IR", "IR"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="counterreporttype",
            name="counter_version",
            field=models.PositiveSmallIntegerField(
                choices=[(4, "COUNTER 4"), (5, "COUNTER 5"), (51, "COUNTER 5.1")]
            ),
        ),
        migrations.AlterField(
            model_name="sushicredentials",
            name="counter_version",
            field=models.PositiveSmallIntegerField(
                choices=[(4, "COUNTER 4"), (5, "COUNTER 5"), (51, "COUNTER 5.1")]
            ),
        ),
    ]
