# Generated by Django 4.2.19 on 2025-02-18 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sushi", "0065_alter_counterreporttype_code_and_more")]

    operations = [
        migrations.AlterField(
            model_name="sushifetchattempt",
            name="credentials",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="sushi.sushicredentials",
            ),
        )
    ]
