# Generated by Django 4.2.19 on 2025-04-08 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from publications.logic.knowledgebase import get_counter_reports


def fill_crtp(apps, schema_editor):
    CounterReportPlatform = apps.get_model("sushi", "CounterReportPlatform")
    CounterReportType = apps.get_model("sushi", "CounterReportType")
    SushiCredentials = apps.get_model("sushi", "SushiCredentials")
    for creds in (e for e in SushiCredentials.objects.all() if e.platform.knowledgebase):
        for counter_version, code in get_counter_reports(creds.platform.knowledgebase):
            if crt := CounterReportType.objects.filter(
                counter_version=counter_version, code=code
            ).first():
                CounterReportPlatform.objects.get_or_create(
                    platform=creds.platform, counter_report=crt
                )


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0026_userorganization_send_harvest_reports"),
        ("publications", "0044_alter_authortoitem_options_author_created_and_more"),
        ("sushi", "0066_alter_sushifetchattempt_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="sushicredentials",
            name="use_counter_reports_from_platform",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CounterReportPlatform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "counter_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sushi.counterreporttype"
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="publications.platform"
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Counter reports to platforms"},
        ),
        migrations.AddConstraint(
            model_name="counterreportplatform",
            constraint=models.UniqueConstraint(
                fields=("counter_report", "platform"), name="unique_crtp"
            ),
        ),
        migrations.RunPython(fill_crtp, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="counterreporttype",
            options={
                "ordering": ["-counter_version", "code"],
                "verbose_name": "COUNTER report type",
                "verbose_name_plural": "COUNTER report types",
            },
        ),
    ]
