# Generated by Django 4.2.20 on 2025-05-06 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def move_last_harvestable_month(apps, schema_editor):
    SushiCredentials = apps.get_model("sushi", "SushiCredentials")
    for creds in SushiCredentials.objects.all():
        if (
            cr2c := creds.counterreportstocredentials_set.filter(
                last_harvestable_month__isnull=False
            )
            .order_by("last_harvestable_month")
            .first()  # lowest value
        ):
            creds.last_harvestable_month = cr2c.last_harvestable_month
            creds.last_harvestable_month_attempt = cr2c.last_harvestable_month_attempt
            creds.last_harvestable_month_user = cr2c.last_harvestable_month_user
            creds.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sushi", "0067_sushicredentials_use_counter_reports_from_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sushicredentials",
            name="last_harvestable_month",
            field=models.DateField(
                help_text="When we know that data before this date are not available", null=True
            ),
        ),
        migrations.AddField(
            model_name="sushicredentials",
            name="last_harvestable_month_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_harvestable_month_credentials",
                to="sushi.sushifetchattempt",
            ),
        ),
        migrations.AddField(
            model_name="sushicredentials",
            name="last_harvestable_month_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_harvestable_month_credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="sushicredentials",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("last_harvestable_month_attempt__isnull", False),
                    ("last_harvestable_month_user__isnull", False),
                    _negated=True,
                ),
                name="last_harvestable_month_by_attempt_vs_user",
            ),
        ),
        migrations.RunPython(move_last_harvestable_month, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="counterreportstocredentials",
            name="last_harvestable_month_by_attempt_vs_user",
        ),
        migrations.RemoveField(
            model_name="counterreportstocredentials", name="last_harvestable_month"
        ),
        migrations.RemoveField(
            model_name="counterreportstocredentials", name="last_harvestable_month_attempt"
        ),
        migrations.RemoveField(
            model_name="counterreportstocredentials", name="last_harvestable_month_user"
        ),
    ]
