# Generated by Django 4.2.24 on 2025-09-15 14:32

from django.db import migrations, models


# IR report for C5.1 requires whitelisting, which is not set by default, so we migrate it here
def set_requires_whitelisting(apps, schema_editor):
    CounterReportType = apps.get_model("sushi", "CounterReportType")
    from sushi.models import COUNTER_REPORTS_REQUIRING_WHITELISTING

    for counter_version, code in COUNTER_REPORTS_REQUIRING_WHITELISTING:
        CounterReportType.objects.filter(code=code, counter_version=counter_version).update(
            requires_whitelisting=True
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "sushi",
            "0068_remove_counterreportstocredentials_last_harvestable_month_by_attempt_vs_user_and_more",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="counterreporttype",
            name="requires_whitelisting",
            field=models.BooleanField(
                default=False,
                help_text="If True, the report requires whitelisting on platform level via "
                "knowledgebase so that it can be assigned to credentials",
            ),
        ),
        migrations.RunPython(set_requires_whitelisting, reverse_code=migrations.RunPython.noop),
    ]
