# Generated by Django 4.2.25 on 2025-10-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sushi", "0069_counterreporttype_requires_whitelisting")]

    operations = [
        migrations.AlterField(
            model_name="sushicredentials",
            name="forced_verified_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Force verified=True for given hash - "
                "useful to preserve verification when URL is automatically updated",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="sushicredentials",
            name="version_hash",
            field=models.CharField(
                db_index=True, help_text="Current hash of model attributes", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="sushifetchattempt",
            name="credentials_version_hash",
            field=models.CharField(
                db_index=True,
                help_text="Hash computed from the credentials at the time this attempt was made",
                max_length=32,
            ),
        ),
    ]
