# Generated by Django 5.2.7 on 2025-11-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sushi", "0070_alter_sushicredentials_forced_verified_hash_and_more")]

    operations = [
        migrations.AlterField(
            model_name="sushicredentials",
            name="counter_reports",
            field=models.ManyToManyField(
                related_name="sushicredentials_set",
                through="sushi.CounterReportsToCredentials",
                through_fields=("credentials", "counter_report"),
                to="sushi.counterreporttype",
            ),
        )
    ]
