# Generated by Django 4.2.22 on 2025-07-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sushi", "0071_alter_sushicredentials_counter_reports")]

    operations = [
        migrations.AlterUniqueTogether(name="sushicredentials", unique_together=set()),
        migrations.AddField(
            model_name="sushicredentials",
            name="to_delete",
            field=models.CharField(
                choices=[
                    ("NO", "No"),
                    ("WITH_DATA", "With Data"),
                    ("WITHOUT_DATA", "Without Data"),
                ],
                default="NO",
            ),
        ),
        migrations.AddConstraint(
            model_name="sushicredentials",
            constraint=models.UniqueConstraint(
                condition=models.Q(("to_delete", "NO")),
                fields=("organization", "platform", "counter_version"),
                name="unique_with_no_delete",
            ),
        ),
    ]
