# Generated by Django 4.2.13 on 2024-06-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("necronomicon", "0002_drop_fk_for_task_result")]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.CharField(
                choices=[
                    ("initial", "Initial"),
                    ("preparing", "Preparing Stats"),
                    ("prepared", "Stats Prepared"),
                    ("delete", "Deleting"),
                    ("deleted", "Deleted"),
                    ("outdated", "Outdated"),
                ],
                default="initial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="batch", name="prepared", field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="batch", name="deleted", field=models.DateTimeField(blank=True, null=True)
        ),
    ]
