# Generated by Django 2.2.13 on 2020-07-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('activity', '0001_initial')]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity', options={'verbose_name_plural': 'User activities'}
        )
    ]
