# Generated by Django 2.2.15 on 2020-10-22 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('scheduler', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='fetchintention',
            name='duplicate_of',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='duplicates',
                to='scheduler.FetchIntention',
            ),
        )
    ]
