# Generated by Django 2.2.16 on 2020-10-30 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('scheduler', '0006_fetchintention_retry_id')]

    operations = [
        migrations.AlterField(
            model_name='fetchintention',
            name='attempt',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='sushi.SushiFetchAttempt',
            ),
        )
    ]
