# Generated by Django 3.1.8 on 2021-05-31 09:03

import django.db.models.deletion
from django.db import migrations, models


def fill_in_previous_intention(apps, schema_editor):
    FetchIntention = apps.get_model('scheduler', 'FetchIntention')
    for fi in FetchIntention.objects.filter(queue_id__isnull=False):
        fi.previous_intention = (
            FetchIntention.objects.filter(queue_id=fi.queue_id, pk__lt=fi.pk)
            .order_by('-pk')
            .first()
        )
        fi.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_fetchintention_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchintention',
            name='previous_intention',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='scheduler.fetchintention',
            ),
        ),
        migrations.RunPython(fill_in_previous_intention, migrations.RunPython.noop),
    ]
