# Generated by Django 3.2.10 on 2022-02-01 13:39
from collections import Counter

from django.db import migrations
from django.db.models import F


def add_empty_import_batch_to_last_3030_attempt(apps, schema_editor):
    ImportBatch = apps.get_model('logs', 'ImportBatch')
    FetchIntention = apps.get_model('scheduler', 'FetchIntention')
    counter = Counter()
    for fi in FetchIntention.objects.filter(
        duplicate_of__isnull=True,
        pk=F('queue__end__pk'),  # last in queue
        attempt__error_code="3030",
        attempt__import_batch__isnull=True,
    ):
        fi.attempt.import_batch = ImportBatch.objects.create(
            report_type=fi.counter_report.report_type,
            platform=fi.credentials.platform,
            organization=fi.credentials.organization,
            date=fi.start_date,
        )
        counter["finalized_count"] += 1

    print()
    print(counter)


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_fetch_intention_queue'),
        ('logs', '0052_remove_importbatch_system_created'),
        ('sushi', '0047_no_data_for_3031_and_3030'),
    ]

    operations = [
        migrations.RunPython(
            add_empty_import_batch_to_last_3030_attempt, migrations.RunPython.noop
        ),
    ]
