# Generated by Django 4.2.14 on 2024-07-26 13:09

from django.db import migrations, models


def adjust_too_many_requests_delay(apps, schema_editor):
    Scheduler = apps.get_model("scheduler", "Scheduler")
    Scheduler.objects.update(too_many_requests_delay=10)
    # Update cooldown to 1 second unless it's already set to something else than 0
    Scheduler.objects.filter(cooldown=0).update(cooldown=1)
    # AIP requests to retry after 5 minutes, so we honor that
    Scheduler.objects.filter(url__icontains="aip.org").update(too_many_requests_delay=300)


class Migration(migrations.Migration):
    dependencies = [("scheduler", "0018_alter_harvest_last_updated_by")]

    operations = [
        migrations.AlterField(
            model_name="scheduler",
            name="too_many_requests_delay",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="scheduler",
            name="cooldown",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Required number of seconds before between queries (to be sure that the "
                "queries are not run in parallel)",
            ),
        ),
        migrations.RunPython(
            adjust_too_many_requests_delay, reverse_code=migrations.RunPython.noop
        ),
    ]
