# Generated by Django 3.2.20 on 2023-08-08 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0008_alter_taggingbatch_source_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTagClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hidden", models.BooleanField(default=True)),
                (
                    "tag_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tags.tagclass"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tag_class")},
            },
        ),
    ]
