# Generated by Django 4.2.6 on 2023-10-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0010_tagging_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='tag_owner_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='tag_owner_org_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='tagclass',
            name='tag_class_owner_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='tagclass',
            name='tag_class_owner_org_not_null',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(('can_see', 50), ('can_assign', 50), _connector='OR'),
                        ('owner__isnull', False),
                    ),
                    models.Q(('can_see', 50), ('can_assign', 50), _connector='OR', _negated=True),
                    _connector='OR',
                ),
                name='tag_owner_not_null',
            ),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ('can_see__in', [20, 30]), ('can_assign__in', [20, 30]), _connector='OR'
                        ),
                        ('owner_org__isnull', False),
                    ),
                    models.Q(
                        models.Q(
                            ('can_see__in', [20, 30]),
                            ('can_assign__in', [20, 30]),
                            _connector='OR',
                            _negated=True,
                        ),
                        ('owner_org__isnull', True),
                    ),
                    _connector='OR',
                ),
                name='tag_owner_org_not_null',
            ),
        ),
        migrations.AddConstraint(
            model_name='tagclass',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ('can_modify', 50),
                            ('can_create_tags', 50),
                            ('default_tag_can_see', 50),
                            ('default_tag_can_assign', 50),
                            _connector='OR',
                        ),
                        ('owner__isnull', False),
                    ),
                    models.Q(
                        ('can_modify', 50),
                        ('can_create_tags', 50),
                        ('default_tag_can_see', 50),
                        ('default_tag_can_assign', 50),
                        _connector='OR',
                        _negated=True,
                    ),
                    _connector='OR',
                ),
                name='tag_class_owner_not_null',
            ),
        ),
        migrations.AddConstraint(
            model_name='tagclass',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ('can_create_tags__in', [20, 30]),
                            ('can_modify__in', [20, 30]),
                            ('default_tag_can_see__in', [20, 30]),
                            ('default_tag_can_assign__in', [20, 30]),
                            _connector='OR',
                        ),
                        ('owner_org__isnull', False),
                    ),
                    models.Q(
                        models.Q(
                            ('can_create_tags__in', [20, 30]),
                            ('can_modify__in', [20, 30]),
                            ('default_tag_can_see__in', [20, 30]),
                            ('default_tag_can_assign__in', [20, 30]),
                            _connector='OR',
                            _negated=True,
                        ),
                        ('owner_org__isnull', True),
                    ),
                    _connector='OR',
                ),
                name='tag_class_owner_org_not_null',
            ),
        ),
    ]
