# Generated by Django 4.2.23 on 2025-07-31 16:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("tags", "0012_alter_organizationtag_last_updated_by_and_more")]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="bg_color",
            field=colorfield.fields.ColorField(
                default="#E2E2E2", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="text_color",
            field=colorfield.fields.ColorField(
                default="#303030", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="tagclass",
            name="bg_color",
            field=colorfield.fields.ColorField(
                default="#E2E2E2", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="tagclass",
            name="text_color",
            field=colorfield.fields.ColorField(
                default="#303030", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
