stages:
  - push
  - image
  - lints
  - tests
  - build

include:
  - local: /.gitlab/github-export.yml
  - local: /.gitlab/test-image.yml
  - local: /.gitlab/pre-commit.yml
  - local: /.gitlab/build-vue.yml
  - local: /.gitlab/run-tests.yml
