stages:
  - export
  - image
  - lints
  - tests
  - build
  - release

include:
  - local: /.gitlab/github-export.yml
  - local: /.gitlab/test-image.yml
  - local: /.gitlab/build-image.yml
  - local: /.gitlab/pre-commit.yml
  - local: /.gitlab/build-vue.yml
  - local: /.gitlab/run-tests.yml
  - local: /.gitlab/test-js.yml
  - local: /.gitlab/sentry.yml
