workflow:
  # Disable multiple runs
  # It should run CI only for MR not for branches when MR exists
  # see https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
  - export
  - image
  - lints
  - tests
  - build
  - release

include:
  - local: /.gitlab/github-export.yml
  - local: /.gitlab/test-image.yml
  - local: /.gitlab/build-image.yml
  - local: /.gitlab/pre-commit.yml
  - local: /.gitlab/build-vue.yml
  - local: /.gitlab/run-tests.yml
  - local: /.gitlab/test-js.yml
  - local: /.gitlab/sentry.yml
