stages:
  - push
  - lints
  - tests
  - build

include:
  - local: /.gitlab/github-export.yml
  - local: /.gitlab/pre-commit.yml

build_vue:
  stage: build
  image: node:10.5.0
  before_script:
    - export "BUILD=yes"
    - export "GIT_VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHA}"
    - export "GIT_COMMITHASH=${CI_COMMIT_SHA}"
    - export "GIT_BRANCH=${CI_COMMIT_REF_NAME:-$CI_COMMIT_SHA}"
  script:
    - cd design/ui
    - npm install
    - npm run build
  artifacts:
    paths:
      - apps/core/static/
  tags:
    - bdd

run_tests:
  stage: tests
  image: ubuntu:bionic  #TODO we can prepare a docker image to speed up the tests
  services:
    - postgres
    - redis
  variables:
    DJANGO_SETTINGS_MODULE: config.settings.test
    POSTGRES_DB: celus
    POSTGRES_USER: celus
    POSTGRES_PASSWORD: celus
    POSTGRES_HOST: postgres
    REDIS_URL: "redis://redis:6379/1"
  before_script:
    - apt-get update
    - apt-get -y install --no-install-recommends ca-certificates git cmake make pkg-config gcc g++ python3-dev python3-pip python3-venv python3-setuptools virtualenv curl libmagic-dev python3-wheel
    - update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    - update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
    - pip install -r requirements/develop.txt
  script:
    - cp config/settings/secret_settings.json.example config/settings/secret_settings.json
    - pytest -v apps
  tags:
    - bdd
