[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.ruff]
line-length = 100
target-version = "py38"

[tool.ruff.lint]
ignore = [
    "A001",  # Variable `Warning` is shadowing a Python builtin
    "A002",  # Argument `id` is shadowing a Python builtin
    "A003",  # Class attribute `list` is shadowing a Python builtin
    "DJ008", # model does not have __str__ method
    "F811",  # redefinition of unused '...'
]
select = [
    'A',  # flake8-builtins
    'B',  # flake8-bugbear
    'DJ', # flake8-django
    'E',  # pycodestyle - errors
    'F',  # pyflakes
    'I',  # isort
    'W',  # pycodestyle - warnings
]
fixable = [
    'I001',
    'F401',
] # I001: imports are incorrectly sorted, F401: unused import

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["B011"] # test files should have asserts

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
skip-magic-trailing-comma = true


[tool.poetry]
name = "celus"
version = "9.0.2"
description = "web application for harvesting and visualization of usage data of electronic information sources"
authors = [
    "Beda Kosata <beda@bigdigdata.com>",
    "Stepan Henek <stepan@bigdigdata.com>",
]
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9.6"

celery = "~5.5.3"
celus-nibbler = "~12.2.1"
celus-nigiri = "~4.1.0"
celus-pycounter = "~4.1.0"
clickhouse-driver = "0.2.9"
colorlog = "^6.7.0"
dj-rest-auth = "~7.0.1"
Django = "~4.2.6"
django-allauth = "~64.2.1"
django-anymail = "^13.0.1"
django-autocomplete-light = "~3.12.1"
django-cachalot = "~2.8.0"
django-celery-results = "~2.6.0"
django-celus-registry = "~0.1.1"
django-colorfield = "^0.14.0"
django-impersonate = "~1.9.1"
django-import-export = "^4.3.9"
django-ipware = "^7.0.1"
django-modeltranslation = "~0.19.16"
django-mptt = "~0.17.0"
django-ntfy = "~0.1.1"
django-otp = "~1.6.1"
django-postgres-copy = "^2.7.0"
django-redis = "^6.0.0"
django-requestlogs = "^0.8.3"
django-reversion = "~5.1.0"
django-test-migrations = "^1.4.0"
djangorestframework = "~3.16.0"
djangorestframework-api-key = "^3.0.0"
drf-nested-routers = "~0.94.2"
hcube = "0.28.0"
isbnlib = "^3.10.3"
lz4 = "~4.4.4"
mrml = "~0.2.0"
numpy = "<2"
openpyxl = "~3.1.2"
pandas = "^2.3.0"
pillow = "^11.3.0"
prometheus-client = "^0.22.1"
psutil = "~7.0.0"
psycopg2-binary = "~2.9.1"
pycountry = "24.6.1"
pydantic = "^2"
pyparsing = "^3.0.9"
python-dateutil = "^2.8.2"
python-decouple = "^3.3"
python-magic = "~0.4.15"
pytz = "*"
pyyaml = "^6.0.1"
redis = "^6.2.0"
requests = "^2.31.0"
rest-pandas = "~1.1.0"
semantic-version = "~2.10.0"
sentry-sdk = "^2.34.1"
toml = "^0.10.2"
XlsxWriter = "^3.2.5"
zstandard = "^0.23.0"
django-sesame = "^3.2.1"
websockets = "^15.0.1"

[tool.poetry.group.dev.dependencies]
deptry = "^0.23.1"
dj-inmemorystorage = "^2.1.0"
django-debug-toolbar = "^6.0.0"
django-extensions = "^4.1"
django-query-counter = "~0.4.0"
django-webtest = "^1.9.7"
factory-boy = "^3.2.1"
faker = "^37.5.3"
filelock = "^3.12.2"
freezegun = "^1.2.2"
pre-commit = "^4.2.0"
pydot = "^4.0.1"
pyfakefs = "^5.0.0"
pytest = "^8.3.3"
pytest-cov = "^6.2.1"
pytest-django = "^4.2.0"
pytest-env = "^1.1.5"
pytest-random-order = "^1.1.0"
pytest-xdist = "^3.3.0"
requests-mock = "~1.12.1"
ruff = "^0.12.7"
sphinx = "^7.2"
watchdog = { extras = ["watchmedo"], version = "^6.0.0" }

[tool.poetry.extras]
registry = ["django-celus-registry"]

[tool.deptry]
known_first_party = ["test_scenarios"]

[tool.deptry.per_rule_ignores]
# some top level imports are not detected properly by deptry
DEP001 = ["config"]
# the following are used internally by django
DEP002 = [
    'colorlog',
    'django-anymail',
    'django-ipware',
    'django-ntfy',
    'django-redis',
    'django-test-migrations',
    'lz4',
    'numpy',                  # used through pandas
    'pillow',
    'psycopg2-binary',
    'python-decouple',
    'pytz',
    'sentry-sdk',
    'toml',
    # the following are used by wsserver
    'aioredis',
    'websockets',
]
# the following are used in tests only, so it does not matter if they are in dev deps only
DEP004 = [
    "pytest",
    "freezegun",
    "faker",
    "factory",
    "clickhouse_driver", # used to setup the test tables
    "filelock",          # used to lock clickhouse test from writing over each other
    "requests_mock",
]
