[project]
name = "celus"
version = "11.1.0"
description = "web application for harvesting and visualization of usage data of electronic information sources"
authors = [
    { name = "Beda Kosata", email = "beda@bigdigdata.com" },
    { name = "Stepan Henek", email = "stepan@bigdigdata.com" },
]
requires-python = ">=3.12.3,<4"
license = "MIT"
dependencies = [
    "celery~=5.6.0",
    "celus-nibbler~=12.4.0",
    "celus-nigiri~=4.2.2",
    "celus-pycounter~=4.1.0",
    "clickhouse-driver==0.2.10",
    "colorlog>=6.7.0,<7",
    "dj-rest-auth~=7.0.1",
    "Django~=5.2.9",
    "django-allauth~=64.2.1",
    "django-anymail>=13.0.1,<14",
    "django-autocomplete-light~=3.12.1",
    "django-cachalot~=2.8.0",
    "django-celery-results~=2.6.0",
    "django-celus-registry~=0.4.0",
    "django-colorfield>=0.14.0,<0.15",
    "django-impersonate~=1.9.1",
    "django-import-export>=4.3.9,<5",
    "django-ipware>=7.0.1,<8",
    "django-modeltranslation~=0.19.16",
    "django-mptt~=0.18.0",
    "django-ntfy~=0.1.1",
    "django-otp~=1.6.1",
    "django-postgres-copy>=2.7.0,<3",
    "django-redis>=6.0.0,<7",
    "django-requestlogs>=0.8.3,<0.9",
    "django-reversion~=6.0.0",
    "django-test-migrations>=1.4.0,<2",
    "djangorestframework~=3.16.0",
    "djangorestframework-api-key>=3.0.0,<4",
    "drf-nested-routers~=0.95.0",
    "hcube==1.0.0",
    "isbnlib>=3.10.3,<4",
    "lz4~=4.4.4",
    "mrml~=0.2.0",
    "numpy~=2.3.4",
    "openpyxl~=3.1.2",
    "pandas>=2.3.0,<3",
    "pillow>=12.0.0,<13",
    "prometheus-client>=0.23.1,<0.24",
    "psutil~=7.1.3",
    "psycopg2-binary~=2.9.1",
    "pycountry==24.6.1",
    "pydantic>=2,<3",
    "pyparsing>=3.0.9,<4",
    "python-dateutil>=2.8.2,<3",
    "python-decouple~=3.3",
    "python-magic~=0.4.15",
    "pytz",
    "pyyaml>=6.0.1,<7",
    "redis>=7.0.1,<8",
    "requests>=2.31.0,<3",
    "semantic-version~=2.10.0",
    "sentry-sdk>=2.34.1,<3",
    "toml>=0.10.2,<0.11",
    "XlsxWriter>=3.2.5,<4",
    "zstandard>=0.25.0,<0.26",
    "django-sesame>=3.2.1,<4",
    "websockets>=15.0.1,<16",
    "pyarrow>=22.0.0,<23",
]

[dependency-groups]
dev = [
    "deptry~=0.24.0",
    "dj-inmemorystorage>=2.1.0,<3",
    "django-debug-toolbar>=6.0.0,<7",
    "django-extensions~=4.1",
    "django-query-counter~=0.4.0",
    "django-webtest>=1.9.7,<2",
    "factory-boy>=3.2.1,<4",
    "faker~=38.0.0",
    "filelock>=3.12.2,<4",
    "freezegun>=1.2.2,<2",
    "pre-commit>=4.2.0,<5",
    "pydot>=4.0.1,<5",
    "pyfakefs>=5.0.0,<6",
    "pytest~=9.0.0",
    "pytest-cov>=7.0.0,<8",
    "pytest-django>=4.11.1,<5",
    "pytest-env>=1.1.5,<2",
    "pytest-random-order>=1.1.0,<2",
    "pytest-xdist>=3.3.0,<4",
    "requests-mock~=1.12.1",
    "ruff~=0.14.9",
    "sphinx~=8.2",
    "watchdog[watchmedo]>=6.0.0,<7",
    "tuna>=0.5.11,<0.6",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.uv]
package = false

[tool.ruff.lint]
ignore = [
    "A001",  # Variable `Warning` is shadowing a Python builtin
    "A002",  # Argument `id` is shadowing a Python builtin
    "A003",  # Class attribute `list` is shadowing a Python builtin
    "DJ008", # model does not have __str__ method
    "F811",  # redefinition of unused '...'
]
select = [
    'A',  # flake8-builtins
    'B',  # flake8-bugbear
    'DJ', # flake8-django
    'E',  # pycodestyle - errors
    'F',  # pyflakes
    'I',  # isort
    'W',  # pycodestyle - warnings
]
fixable = [
    'I001',
    'F401',
] # I001: imports are incorrectly sorted, F401: unused import

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["B011"] # test files should have asserts

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.deptry]
known_first_party = ["test_scenarios"]

[tool.deptry.per_rule_ignores]
# some top level imports are not detected properly by deptry
DEP001 = ["config"]
# the following are used internally by django
DEP002 = [
    'colorlog',
    'django-anymail',
    'django-ipware',
    'django-ntfy',
    'django-redis',
    'django-test-migrations',
    'lz4',
    'numpy',                  # used through pandas
    'pillow',
    'psycopg2-binary',
    'python-decouple',
    'pytz',
    'sentry-sdk',
    'toml',
    # the following are used by wsserver
    'aioredis',
    'websockets',
]
# the following are used in tests only, so it does not matter if they are in dev deps only
DEP004 = [
    "pytest",
    "freezegun",
    "faker",
    "factory",
    "clickhouse_driver", # used to setup the test tables
    "filelock",          # used to lock clickhouse test from writing over each other
    "requests_mock",
]
