[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 100
skip-string-normalization = true

[tool.poetry]
name = "celus"
version = "1.0.9"
description = "web application for harvesting and visualization of usage data of electronic information sources"
authors = ["Beda Kosata <beda@bigdigdata.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

celery = "~4.4.2"
dateparser = "~0.7.4"
Django = "~2.2.0"
django-allauth = "~0.41.0"
django-anymail = "~7.1.0"
django-celery-results = "~1.2.0"
django-cachalot = {git = "https://github.com/beda42/django-cachalot.git", rev = "30d899f"}
django-debug-toolbar = { version = "~2.2.0", optional = true }
django-error-report = "~0.2.0"
django-livereload-server= { version = "~0.3.2", optional = true }
django-modeltranslation = "~0.15.0"
django-mptt = "~0.11.0"
django-prometheus = "~2.0.0"
django-redis = "~4.11.0"
django-reversion = "~3.0.7"
django-querycount = { version = "~0.7.0", optional = true }
djangorestframework = "~3.11.0"
drf-nested-routers = "~0.91.0"
jupyter = { version = "~1.0.0", optional = true }
lz4 = "~3.0.2"
pycounter = {git = "https://github.com/beda42/pycounter.git", branch = "beda"}
python-magic = "~0.4.15"
pytz = "*"
pytest = { version = "~5.4.1", optional = true }
pytest-cov = { version = "~2.8.1", optional = true }
pytest-django = { version = "~3.9.0", optional = true }
django-webtest = { version = "~1.9.7", optional = true }
requests-mock = { version = "~1.8.0", optional = true }
pyfakefs = { version = "~4.0.2", optional = true }
Faker = { version = "~4.0.3", optional = true }
factory-boy = { version = "~2.12.0", optional = true }
psutil = "~5.7.0"
psycopg2-binary = "~2.8.5"
redis = "~3.5.0"
rest-pandas = "~1.1.0"
sphinx = { version = "~3.0.3", optional = true }

[tool.poetry.extras]
production = ["pycounter"]
staging = ["pycounter"]
test = ["pycounter", "pytest", "pytest-cov", "pytest-django", "django-webtest", "requests-mock", "pyfakefs", "Faker", "factory-boy"]
devel = [
	"pycounter", "pytest", "pytest-cov", "pytest-django", "django-webtest", "requests-mock", "pyfakefs", "Faker", "factory-boy",
	"test", "sphinx", "django-debug-toolbar", "django-livereload-server", "jupyter", "django-querycount",
]

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
