# Generated by Django 2.2.14 on 2020-07-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('sites', '0002_alter_domain_unique')]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('img', models.ImageField(upload_to='deployment')),
                ('alt_text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                (
                    'site',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
                ),
            ],
            options={'unique_together': {('site',)}},
        ),
        migrations.CreateModel(
            name='FooterImage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('img', models.ImageField(upload_to='deployment')),
                ('alt_text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                (
                    'position',
                    models.PositiveSmallIntegerField(
                        help_text='influences sorting of images on page'
                    ),
                ),
                (
                    'site',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
                ),
            ],
            options={'unique_together': {('site', 'position')}},
        ),
    ]
