# Generated by Django 3.2.12 on 2022-03-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('api', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='organizationapikey',
            name='hashed_key',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='organizationapikey',
            name='id',
            field=models.CharField(
                editable=False, max_length=150, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
