# Generated by Django 2.2.5 on 2019-09-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_annotation_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='owner_level',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (100, 'Normal user'),
                    (200, 'Robot'),
                    (300, 'Organization admin'),
                    (400, 'Consortium staff'),
                    (1000, 'Consortium admin'),
                ],
                default=300,
                help_text='Level of user who created this record - used to determine who can modify it',
            ),
        ),
    ]
