# Generated by Django 2.2.5 on 2019-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_chartdefinition_ignore_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdataview',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='reportdataview',
            name='is_standard_view',
            field=models.BooleanField(default=True, help_text='Standard view are shown separately from other views'),
        ),
        migrations.AddField(
            model_name='reportdataview',
            name='position',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
