# Generated by Django 3.1.3 on 2020-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_datasource_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionfilter',
            name='allowed_values',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='reportdataview',
            name='metric_allowed_values',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
