# Generated by Django 4.2.11 on 2024-05-06 13:45

from django.db import migrations
from django.db.models import Count


def redefine_standard_views(apps, schema_editor):
    ReportDataView = apps.get_model("charts", "ReportDataView")
    for rdv in ReportDataView.objects.all().annotate(has_filters=Count("dimension_filters")):
        standard_view = bool(rdv.has_filters or len(rdv.metric_allowed_values) > 0)
        rdv.is_standard_view = standard_view
        rdv.save()


class Migration(migrations.Migration):
    dependencies = [("charts", "0012_tr_j1_unique_item_requests")]

    operations = [
        migrations.RunPython(redefine_standard_views, reverse_code=migrations.RunPython.noop)
    ]
