# Generated by Django 4.2.16 on 2025-01-10 11:25

from django.db import migrations


def remove_full_suffix(apps, schema_editor):
    ReportDataView = apps.get_model("charts", "ReportDataView")
    for rdv in ReportDataView.objects.filter(short_name__endswith="_FULL"):
        rdv.short_name = rdv.short_name[: -len("_FULL")]
        rdv.save()


class Migration(migrations.Migration):
    dependencies = [("charts", "0013_redefine_standard_views")]

    operations = [migrations.RunPython(remove_full_suffix, reverse_code=migrations.RunPython.noop)]
