# Generated by Django 4.2.19 on 2025-04-11 06:33

from django.db import migrations


def switch_to_metric_dimension(apps, schema_editor):
    """
    Switch all charts which have Interest_Type as primary dimension to use
    Metric implicit_dimension instead.
    If a chart with the resulting configuration already exists, the chart
    at hand will be deleted.
    """
    ChartDefinition = apps.get_model("charts", "ChartDefinition")
    Dimension = apps.get_model("logs", "Dimension")
    try:
        itdim = Dimension.objects.get(short_name="Interest_Type")
    except Dimension.DoesNotExist:
        return

    # find all charts with Interest_Type as primary dimension
    for chart in ChartDefinition.objects.filter(primary_dimension=itdim):
        if ChartDefinition.objects.filter(
            primary_dimension=None,
            primary_implicit_dimension="metric",
            secondary_dimension=chart.secondary_dimension,
            secondary_implicit_dimension=chart.secondary_implicit_dimension,
        ).exists():
            chart.delete()
        else:
            chart.primary_dimension = None
            chart.primary_implicit_dimension = "metric"
            chart.save()
    # find all charts with Interest_Type as secondary dimension
    for chart in ChartDefinition.objects.filter(secondary_dimension=itdim):
        if ChartDefinition.objects.filter(
            primary_dimension=chart.primary_dimension,
            primary_implicit_dimension=chart.primary_implicit_dimension,
            secondary_dimension=None,
            secondary_implicit_dimension="metric",
        ).exists():
            chart.delete()
        else:
            chart.secondary_dimension = None
            chart.secondary_implicit_dimension = "metric"
            chart.save()


class Migration(migrations.Migration):
    dependencies = [("charts", "0014_remove_full_suffix")]

    operations = [migrations.RunPython(switch_to_metric_dimension, migrations.RunPython.noop)]
