# Generated by Django 3.1.3 on 2021-01-05 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='FlexibleDataExport',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'not started'), (1, 'in progress'), (2, 'finished')], default=0
                    ),
                ),
                ('extra_info', models.JSONField(default=dict, help_text='Internal stuff')),
                ('output_file', models.FileField(upload_to='export')),
                (
                    'export_params',
                    models.JSONField(default=dict, help_text='Serialized parameters of the export'),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={'abstract': False},
        )
    ]
