# Generated by Django 3.1.6 on 2021-04-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0002_auto_20210329_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexibledataexport',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
