# Generated by Django 3.1.8 on 2021-04-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0003_created_autoaddnow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexibledataexport',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'not started'), (1, 'in progress'), (2, 'finished'), (3, 'error')],
                default=0,
            ),
        ),
    ]
