# Generated by Django 3.2.12 on 2022-03-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0004_export_status_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibledataexport',
            name='file_format',
            field=models.CharField(
                choices=[('XLSX', 'XLSX'), ('ZIP_CSV', 'CSV files inside ZIP archive')],
                default='XLSX',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='flexibledataexport',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
