# Generated by Django 3.2.18 on 2023-04-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0005_flexibledataexport_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexibledataexport',
            name='file_format',
            field=models.CharField(
                choices=[
                    ('XLSX', 'XLSX'),
                    ('XLSX_NO_CHARTS', 'XLSX without charts'),
                    ('ZIP_CSV', 'CSV files inside ZIP archive'),
                ],
                default='XLSX',
                max_length=16,
            ),
        ),
    ]
