# Generated by Django 4.2.11 on 2024-05-03 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0024_alter_userorganization_unique_together"),
        ("logs", "0083_alter_importbatchsynclog_last_updated_by_and_more"),
        ("export", "0006_alter_flexibledataexport_file_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlexibleDataAPIExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "not started"),
                            (1, "in progress"),
                            (2, "finished"),
                            (3, "error"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "extra_info",
                    models.JSONField(blank=True, default=dict, help_text="Internal stuff"),
                ),
                ("output_file", models.FileField(blank=True, null=True, upload_to="export")),
                (
                    "start_date",
                    models.DateField(help_text="May override the report's start date", null=True),
                ),
                (
                    "end_date",
                    models.DateField(help_text="May override the report's end date", null=True),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("XLSX", "XLSX"),
                            ("XLSX_NO_CHARTS", "XLSX without charts"),
                            ("ZIP_CSV", "CSV files inside ZIP archive"),
                        ],
                        default="XLSX_NO_CHARTS",
                        max_length=16,
                    ),
                ),
                (
                    "owner_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logs.flexiblereport"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
