# Generated by Django 3.1.3 on 2020-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('knowledgebase', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='importattempt', name='stats', field=models.JSONField(blank=True, null=True)
        )
    ]
