# Generated by Django 3.2.13 on 2022-06-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('knowledgebase', '0003_routersyncattempt')]

    operations = [
        migrations.CreateModel(
            name='ReportTypeImportAttempt',
            fields=[],
            options={'proxy': True, 'indexes': [], 'constraints': []},
            bases=('knowledgebase.importattempt',),
        ),
        migrations.AlterField(
            model_name='importattempt',
            name='kind',
            field=models.CharField(
                choices=[('platform', 'Platform'), ('report_type', 'Report type')], max_length=20
            ),
        ),
    ]
