# Generated by Django 3.2.15 on 2022-08-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_report_type_in_knowledgebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserDefinitionImportAttempt',
            fields=[],
            options={'proxy': True, 'indexes': [], 'constraints': [],},
            bases=('knowledgebase.importattempt',),
        ),
        migrations.AlterField(
            model_name='importattempt',
            name='kind',
            field=models.CharField(
                choices=[
                    ('platform', 'Platform'),
                    ('report_type', 'Report type'),
                    ('parser_definition', 'Parser definition'),
                ],
                max_length=20,
            ),
        ),
    ]
