# Generated by Django 4.2.20 on 2025-04-22 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("celus_registry", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("celus_registry.platform",),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[],
            options={
                "ordering": ("counter_release", "report_id"),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("celus_registry.report",),
        ),
        migrations.CreateModel(
            name="SushiService",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
                "ordering": ("counter_release",),
            },
            bases=("celus_registry.sushiservice",),
        ),
        migrations.CreateModel(
            name="PlatformExtras",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("knowledgebase", models.JSONField()),
                (
                    "platform",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="counter_registry.platform"
                    ),
                ),
            ],
        ),
    ]
