# Generated by Django 2.2.1 on 2019-06-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='doi',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
