# Generated by Django 2.2.1 on 2019-08-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('publications', '0004_pub_type_verbose_name')]

    operations = [
        migrations.AlterModelOptions(name='title', options={'ordering': ('name', 'pub_type')})
    ]
