# Generated by Django 2.2.5 on 2019-09-23 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_timestamps'),
        ('publications', '0011_unlocalize_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.DataSource',
            ),
        ),
    ]
