# Generated by Django 2.2.5 on 2019-10-23 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def fill_platforminterestreport_m2m(apps, schema_editor):
    platform_cls = apps.get_model('publications', 'Platform')
    pir_cls = apps.get_model('publications', 'PlatformInterestReport')
    for platform in platform_cls.objects.all():
        for report_type in platform.interest_reports.all():
            pir_cls.objects.create(report_type=report_type, platform=platform)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0025_modification_dates'),
        ('publications', '0012_platform_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform', name='last_modified', field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PlatformInterestReport',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                (
                    'platform',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='publications.Platform'
                    ),
                ),
                (
                    'report_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='logs.ReportType'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='interest_reports_through',
            field=models.ManyToManyField(
                related_name='interest_platforms',
                through='publications.PlatformInterestReport',
                to='logs.ReportType',
            ),
        ),
        migrations.RunPython(fill_platforminterestreport_m2m, noop),
    ]
