# Generated by Django 2.2.9 on 2020-01-31 08:12
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_platformtitle'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(
            """CREATE INDEX publications_title_name_trgm ON publications_title
                   USING GIN (name gin_trgm_ops);
               CREATE INDEX publications_title_isbn_trgm ON publications_title
                   USING GIN (isbn gin_trgm_ops);
               CREATE INDEX publications_title_issn_trgm ON publications_title
                   USING GIN (issn gin_trgm_ops);
               CREATE INDEX publications_title_doi_trgm ON publications_title
                   USING GIN (doi gin_trgm_ops);
            """,
            """DROP INDEX publications_title_name_trgm;
               DROP INDEX publications_title_isbn_trgm;
               DROP INDEX publications_title_issn_trgm;
               DROP INDEX publications_title_doi_trgm;
               """,
        ),
    ]
