# Generated by Django 2.2.10 on 2020-04-14 12:36

import sys

from django.db import migrations
from django.db.models import Max, Count


def remove_duplicities(apps, schema_editor):
    PlatformTitle = apps.get_model('publications', 'PlatformTitle')
    duplicities = (
        PlatformTitle.objects.values('title_id', 'platform_id', 'organization_id', 'date')
        .order_by()
        .annotate(max_pk=Max('pk'), count=Count('pk'))
        .filter(count__gt=1)
    )

    print(f"Total records: {PlatformTitle.objects.count()}", file=sys.stderr)
    distinct = (
        PlatformTitle.objects.values('title_id', 'platform_id', 'organization_id', 'date')
        .distinct()
        .count()
    )
    print(f"Distinct records: {distinct}", file=sys.stderr)

    total_count = 0
    dup_count = 0
    for duplicity in duplicities:
        field_filter = {k: v for k, v in duplicity.items() if k not in ('max_pk', 'count')}
        count, _ = (
            PlatformTitle.objects.filter(**field_filter).exclude(pk=duplicity['max_pk']).delete()
        )
        total_count += count
        dup_count += 1

    print(f"Removed: {total_count} duplicities from {dup_count} unique records", file=sys.stderr)
    print(f"New total: {PlatformTitle.objects.count()}", file=sys.stderr)


class Migration(migrations.Migration):

    dependencies = [('publications', '0016_title_trgm_index')]

    operations = [migrations.RunPython(remove_duplicities, reverse_code=migrations.RunPython.noop)]
