# Generated by Django 2.2.10 on 2020-04-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_nullable_ico'),
        ('publications', '0017_platformtitle_unique_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platformtitle', unique_together={('title', 'platform', 'organization', 'date')}
        )
    ]
