# Generated by Django 2.2.14 on 2020-08-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0019_more_pub_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='ext_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
