# Generated by Django 3.1.6 on 2021-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0023_jsonfield'),
    ]

    operations = [
        migrations.AlterUniqueTogether(name='platform', unique_together=set(),),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(
                fields=('ext_id', 'source'), name='ext_id_source_not_null'
            ),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(
                condition=models.Q(source=None), fields=('ext_id',), name='ext_id_source_null'
            ),
        ),
    ]
