# Generated by Django 3.2.7 on 2021-10-19 10:53

"""
This is a one-off fix for platforms with empty `name`. It uses the `short_name` to populate `name`
in such cases.

The rationale behind this is that it should not be possible to create platforms with empty name,
so we have no idea how they appeared in the first place. But if we assume it will not happen again
in the future, we can apply this migration and have it fixed.

Also, a migration is a convenient way how to fix it in all Celus installations.
"""


from django.db import migrations
from django.db.models import F


def fill_empty_platform_name(apps, schema_editor):
    Platform = apps.get_model('publications', 'Platform')
    # fill in just the en version of the name, it should be sufficient
    Platform.objects.filter(name_en='').update(name_en=F('short_name'))


class Migration(migrations.Migration):

    dependencies = [('publications', '0026_title_type_data_migration')]

    operations = [migrations.RunPython(fill_empty_platform_name, migrations.RunPython.noop)]
