# Generated by Django 3.2.12 on 2022-02-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('publications', '0027_fill_platform_name')]

    operations = [
        migrations.AddField(
            model_name='title', name='proprietary_ids', field=models.JSONField(default=list)
        ),
        migrations.AddField(model_name='title', name='uris', field=models.JSONField(default=list)),
    ]
