# Generated by Django 3.2.12 on 2022-03-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0027_fill_platform_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform', options={'ordering': ('short_name',), 'verbose_name': 'Platform'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name', 'pub_type'), 'verbose_name': 'Title/Database'},
        ),
    ]
