# Generated by Django 3.2.12 on 2022-03-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0028_verbose_names'),
        ('publications', '0029_title_default_pub_type'),
    ]

    operations = []
