# Generated by Django 3.2.12 on 2022-04-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('publications', '0030_merge_0028_verbose_names_0029_title_default_pub_type')]

    operations = [
        migrations.AlterUniqueTogether(
            name='title',
            unique_together={('name', 'isbn', 'issn', 'eissn', 'doi', 'proprietary_ids')},
        )
    ]
