# Generated by Django 3.2.13 on 2022-05-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('publications', '0031_alter_title_unique_together')]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='counter_registry_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(
                fields=('counter_registry_id',), name='unique_counter_registry_id'
            ),
        ),
    ]
