# Generated by Django 3.2.15 on 2022-10-05 11:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('publications', '0032_counter_registry_id')]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='duplicates',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                help_text="Links to other platform's ext_id",
                size=None,
            ),
        )
    ]
