# Generated by Django 3.2.15 on 2022-10-20 10:28

from django.db import migrations
from django.db.models import Q
from logs.logic.validation import normalize_issn


def renormalize_issns(apps, schema_editor):
    Title = apps.get_model('publications', 'Title')
    for title in Title.objects.filter(
        Q(issn__regex=r'^\d+[xX]?$') | Q(eissn__regex=r'^\d+[xX]?$')
    ).iterator():
        title.issn = normalize_issn(title.issn, raise_error=False)
        title.eissn = normalize_issn(title.eissn, raise_error=False)
        title.save()


class Migration(migrations.Migration):

    dependencies = [('publications', '0033_platform_duplicates')]

    operations = [migrations.RunPython(renormalize_issns, migrations.RunPython.noop)]
