# Generated by Django 3.2.16 on 2022-11-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_extra_data_dismissed_and_seen_last_release'),
        ('publications', '0034_issn_renormalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.datasource',
            ),
        ),
    ]
