# Generated by Django 3.2.18 on 2023-04-03 14:04

from django.db import migrations


def add_ir_m1_as_interest_to_all_platforms(apps, schema_editor):
    Platform = apps.get_model('publications', 'Platform')
    ReportType = apps.get_model('logs', 'ReportType')
    PlatformInterestReport = apps.get_model('publications', 'PlatformInterestReport')
    try:
        ir_m1 = ReportType.objects.get(short_name='IR_M1')
    except ReportType.DoesNotExist:
        pass
    else:
        for platform in Platform.objects.all():
            PlatformInterestReport.objects.get_or_create(report_type=ir_m1, platform=platform)


class Migration(migrations.Migration):
    dependencies = [('publications', '0036_titleoverlapbatch')]

    operations = [
        migrations.RunPython(
            add_ir_m1_as_interest_to_all_platforms, reverse_code=migrations.RunPython.noop
        )
    ]
