# Generated by Django 3.2.19 on 2023-08-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('publications', '0037_add_ir_m1_interest_to_all_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='eissn',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='ISSN of electronic version',
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name='title',
            name='issn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=9),
        ),
    ]
