# Generated by Django 4.2.11 on 2024-05-27 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("publications", "0039_alter_titleoverlapbatch_last_updated_by")]

    operations = [migrations.AlterUniqueTogether(name="title", unique_together=set())]
