# Generated by Django 4.2.11 on 2024-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("publications", "0040_alter_title_unique_together")]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("isni", models.CharField(blank=True, default="", max_length=16)),
                ("orcid", models.CharField(blank=True, default="", max_length=16)),
            ],
            options={"unique_together": {("name", "isni", "orcid")}},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("doi", models.CharField(max_length=250, blank=True, default="")),
                ("isbn", models.CharField(blank=True, default="", max_length=20)),
                ("issn", models.CharField(blank=True, db_index=True, default="", max_length=9)),
                (
                    "eissn",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="ISSN of electronic version",
                        max_length=9,
                    ),
                ),
                ("uris", models.JSONField(default=list, blank=True)),
                ("proprietary_ids", models.JSONField(default=list, blank=True)),
            ],
            options={"verbose_name": "Item", "ordering": ("name", "publication_date")},
        ),
        migrations.CreateModel(
            name="AuthorToItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Used for per title author ordering"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, to="publications.author"),
                ),
                (
                    "item",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, to="publications.item"),
                ),
            ],
            options={"unique_together": {("author", "item")}},
        ),
        migrations.AddField(
            model_name="author",
            name="items",
            field=models.ManyToManyField(
                related_name="authors", through="publications.AuthorToItem", to="publications.item"
            ),
        ),
    ]
