# Generated by Django 4.2.15 on 2024-08-21 11:37

from django.db import migrations, models

import publications.models


class Migration(migrations.Migration):
    dependencies = [("publications", "0041_item")]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="sushi_arrival_stats",
            field=models.JSONField(
                blank=True,
                default=publications.models.default_stats,
                help_text="Stats about when a specific percentage of reports are typically "
                "available",
            ),
        )
    ]
