# Generated by Django 4.2.16 on 2024-10-09 11:44

from django.db import migrations, models


def remove_ext_ids_for_null_sources(apps, schema_editor):
    Platform = apps.get_model("publications", "Platform")
    Platform.objects.filter(source__isnull=True, ext_id__isnull=False).update(ext_id=None)


class Migration(migrations.Migration):
    dependencies = [("publications", "0042_platform_sushi_arrival_stats")]

    operations = [
        migrations.RunPython(
            remove_ext_ids_for_null_sources, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveConstraint(model_name="platform", name="ext_id_source_null"),
        migrations.AddConstraint(
            model_name="platform",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("source", None), ("ext_id", None)),
                    models.Q(("source", None), _negated=True),
                    _connector="OR",
                ),
                name="if_source_is_null_ext_id_should_be_null",
            ),
        ),
    ]
