# Generated by Django 4.2.15 on 2024-10-14 10:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("publications", "0043_remove_platform_ext_id_source_null_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authortoitem", options={"ordering": ("item_id", "author_id", "position")}
        ),
        migrations.AddField(
            model_name="author",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="author", name="last_updated", field=models.DateTimeField(auto_now=True)
        ),
        migrations.AddField(
            model_name="author",
            name="last_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="item", name="last_updated", field=models.DateTimeField(auto_now=True)
        ),
        migrations.AddField(
            model_name="item",
            name="last_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="pub_type",
            field=models.CharField(
                choices=[
                    ("B", "Book"),
                    ("J", "Journal"),
                    ("U", "Unknown"),
                    ("D", "Database"),
                    ("O", "Other"),
                    ("R", "Report"),
                    ("N", "Newspaper"),
                    ("M", "Multimedia"),
                    ("A", "Article"),
                    ("S", "Book segment"),
                    ("T", "Dataset"),
                    ("P", "Platform"),
                    ("I", "Repository item"),
                    ("H", "Thesis or dissertation"),
                ],
                default="U",
                max_length=1,
                verbose_name="Publication type",
            ),
        ),
        migrations.AddField(
            model_name="title",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="title", name="last_updated", field=models.DateTimeField(auto_now=True)
        ),
        migrations.AddField(
            model_name="title",
            name="last_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="author", name="name", field=models.CharField(blank=True, max_length=250)
        ),
    ]
