# Generated by Django 4.2.19 on 2025-04-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0044_alter_authortoitem_options_author_created_and_more"),
        ("sushi", "0067_sushicredentials_use_counter_reports_from_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="counter_reports_source",
            field=models.CharField(
                choices=[("knowledgebase", "Knowledgebase"), ("manual", "Manual")],
                default="knowledgebase",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="platform",
            name="counter_reports",
            field=models.ManyToManyField(
                related_name="sushicredentials_via_platform",
                through="sushi.CounterReportPlatform",
                to="sushi.counterreporttype",
            ),
        ),
    ]
