# Generated by Django 4.2.19 on 2025-04-04 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("publications", "0045_platform_counter_reports_source")]

    operations = [
        migrations.RemoveField(model_name="platform", name="interest_reports"),
        migrations.DeleteModel(name="PlatformInterestReport"),
    ]
