# Generated by Django 2.2.15 on 2020-08-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('recache', '0002_add_stats')]

    operations = [
        migrations.AddField(
            model_name='cachedquery',
            name='origin',
            field=models.CharField(
                blank=True, help_text="Optional identifier of the query's origin", max_length=32
            ),
        )
    ]
