# Generated by Django 2.2.15 on 2020-08-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('recache', '0003_cachedquery_origin')]

    operations = [
        migrations.AlterField(
            model_name='cachedquery',
            name='origin',
            field=models.CharField(
                blank=True,
                help_text="Optional identifier of the query's origin. "
                "For info only, is not used when querying for cached queries",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='cachedquery',
            name='query_hash',
            field=models.CharField(
                help_text='Hash of the query string', max_length=32, unique=True
            ),
        ),
    ]
