# Generated by Django 2.2.15 on 2020-08-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('recache', '0004_unique_query_hash')]

    operations = [migrations.RemoveField(model_name='cachedquery', name='query_pickle')]
