# Generated by Django 2.2.15 on 2020-09-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('recache', '0005_remove_cachedquery_query_pickle')]

    operations = [
        migrations.AlterField(
            model_name='cachedquery',
            name='query_hash',
            field=models.CharField(help_text='Hash of the query string', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='cachedquery', unique_together={('query_hash', 'django_version')}
        ),
    ]
