# Generated by Django 3.2.18 on 2023-03-27 08:36

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('recache', '0006_query_hash_unique_with_django_version')]

    operations = [
        migrations.AlterField(
            model_name='cachedquery',
            name='lifetime',
            field=models.DurationField(
                default=datetime.timedelta(days=10),
                help_text='Number of seconds from last querying after which the cache will be '
                'removed',
            ),
        )
    ]
