# Generated by Django 3.2.18 on 2023-03-28 08:56
"""
This data migration removes caches which would no longer be valid after the
recent changes to the lifetime of cached queries and introduction of the duration threshold.
"""
from datetime import timedelta

from django.db import migrations
from django.db.models import DateTimeField, ExpressionWrapper, F
from django.utils.timezone import now


def remove_obsolete_caches(apps, schema_editor):
    CachedQuery = apps.get_model("recache", "CachedQuery")
    # remove caches faster than 20ms
    CachedQuery.objects.filter(query_durations__0__lt=0.02).delete()
    # remove caches older than 10 days
    CachedQuery.objects.annotate(
        live_until=ExpressionWrapper(
            F("last_queried") + timedelta(days=10), output_field=DateTimeField()
        )
    ).filter(live_until__lt=now()).delete()


class Migration(migrations.Migration):
    dependencies = [("recache", "0007_alter_cachedquery_lifetime")]

    operations = [migrations.RunPython(remove_obsolete_caches, migrations.RunPython.noop)]
