# Generated by Django 2.2.1 on 2019-07-01 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('organizations', '0003_non_unique_ico'), ('core', '0002_identity')]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('short_name', models.SlugField()),
                (
                    'type',
                    models.PositiveSmallIntegerField(choices=[(1, 'API'), (2, 'Organization')]),
                ),
                ('url', models.URLField(blank=True)),
                (
                    'organization',
                    models.OneToOneField(
                        blank=True,
                        help_text='Used to define data sources private to an organization',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='private_data_source',
                        to='organizations.Organization',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='identity',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.DataSource',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.DataSource',
            ),
        ),
    ]
