# Generated by Django 2.2.1 on 2019-07-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('core', '0003_datasource')]

    operations = [
        migrations.AlterModelOptions(name='identity', options={'verbose_name_plural': 'identities'})
    ]
