# Generated by Django 2.2.14 on 2020-07-28 12:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('core', '0007_timestamps')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, help_text='User state data that do not deserve a dedicated field'
            ),
        )
    ]
