# Generated by Django 3.1.8 on 2021-05-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210329_1002'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(
                condition=models.Q(type=2),
                fields=('short_name',),
                name='source-unique-global-short_name',
            ),
        ),
    ]
