# Generated by Django 3.2.13 on 2022-06-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0010_remove_duplicate_indices'),
        ('core', '0015_unique_name_within_organization_data_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[],
            options={'proxy': True, 'indexes': [], 'constraints': []},
            bases=('django_celery_results.taskresult',),
        ),
    ]
