# Generated by Django 3.2.19 on 2023-06-06 05:42
from django.contrib.postgres.operations import CryptoExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("core", "0017_user_extra_data_dismissed_and_seen_last_release")]

    operations = [CryptoExtension()]
