# Generated by Django 3.2.19 on 2023-06-27 15:53

from django.db import migrations

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_pgcrypto'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.CelusUserManager()),
            ],
        ),
    ]
