# Generated by Django 4.2.10 on 2024-02-23 10:58

from django.db import migrations


def create_otp_devices(apps, schema_editor):
    EmailDevice = apps.get_model("otp_email", "EmailDevice")
    User = apps.get_model("core", "User")
    for user in User.objects.all():
        EmailDevice.objects.get_or_create(
            user=user,
            name="default",
            defaults={
                "confirmed": True,
                "email": None,  # None means the default email will be used
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_user_managers"),
        ("otp_email", "0005_emaildevice_last_generated_timestamp"),
    ]

    operations = [migrations.RunPython(create_otp_devices, reverse_code=migrations.RunPython.noop)]
