# Generated by Django 4.2.11 on 2024-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0020_otp_devices")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="skip_2fa",
            field=models.BooleanField(
                default=False, help_text="If set to True, 2FA auth will be bypassed"
            ),
        )
    ]
