# Generated by Django 4.2.16 on 2024-12-13 09:42

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0021_user_skip_2fa")]

    operations = [
        migrations.AlterModelOptions(name="user", options={}),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email", ""), _negated=True),
                name="unique-user-email",
            ),
        ),
    ]
