# Generated by Django 4.2.19 on 2025-04-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0022_alter_user_options_user_unique_user_email")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="send_grouped_harvest_reports",
            field=models.BooleanField(default=False),
        )
    ]
