# Generated by Django 4.2.23 on 2025-08-22 11:03

import sys

from django.db import migrations


def lowercase_emailaddress(apps, schema_editor):
    EmailAddress = apps.get_model("account", "EmailAddress")
    User = apps.get_model("core", "User")
    to_delete = []
    for email_address in EmailAddress.objects.all():
        if email_address.email != email_address.email.lower():
            # check if lowercased version exists
            if correct := EmailAddress.objects.filter(
                user_id=email_address.user_id, email=email_address.email.lower()
            ).first():
                if email_address.verified and not correct.verified:
                    # verify the correct lowercased address, to preserve the verified status
                    print(f"Verifying {correct.email} for user {correct.user_id}", file=sys.stderr)
                    correct.verified = True
                    correct.save()
                to_delete.append(email_address.pk)
            else:
                # no lowercased version exists, so we can just save the email address
                email_address.email = email_address.email.lower()
                email_address.save()

    if to_delete:
        addrs = EmailAddress.objects.filter(pk__in=to_delete).values_list("email", flat=True)
        print(
            f"Deleting {len(to_delete)} duplicated email addresses: {', '.join(addrs)}",
            file=sys.stderr,
        )
        EmailAddress.objects.filter(pk__in=to_delete).delete()

    for user in User.objects.all():
        if user.email != user.email.lower():
            user.email = user.email.lower()
            user.save()


class Migration(migrations.Migration):
    dependencies = [("core", "0023_user_send_grouped_harvest_reports")]

    operations = [migrations.RunPython(lowercase_emailaddress, migrations.RunPython.noop)]
