version: '3.4'
services:
  postgres:
    container_name: "celus-postgres"
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
  web:
    container_name: "celus-django"
    image: registry.gitlab.com/big-dig-data/celus/celus-django
    expose:
      - 8000
    entrypoint: /var/www/celus/entrypoint-web.sh
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - REDIS_LOCATION=${REDIS_LOCATION}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - redis
      - postgres
  nginx:
    container_name: "celus-nginx"
    image: registry.gitlab.com/big-dig-data/celus/celus-nginx
    expose:
      - 80
    ports:
      - 8080:80
    depends_on:
      - web
  redis:
    container_name: "celus-redis"
    image: redis
  celery-worker:
    container_name: "celus-celery-worker"
    image: registry.gitlab.com/big-dig-data/celus/celus-django
    entrypoint: /var/www/celus/start_celery.sh
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - REDIS_LOCATION=${REDIS_LOCATION}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - redis
      - postgres
  celery-beat:
    container_name: "celus-celery-beat"
    image: registry.gitlab.com/big-dig-data/celus/celus-django
    entrypoint: /var/www/celus/start_celerybeat.sh
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - REDIS_LOCATION=${REDIS_LOCATION}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - redis
      - postgres
