version: '3.4'
services:
  postgres:
    container_name: "celus-postgres"
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
  web:
    container_name: "celus-django"
    build:
      context: ..
      target: celus-django
    image: "celus-django"
    expose: 
      - 8000
    entrypoint: /var/www/celus/entrypoint-web.sh
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ERMS_API_URL=${ERMS_API_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - REDIS_LOCATION=${REDIS_LOCATION}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - redis
      - postgres
  nginx:
    container_name: "celus-nginx"
    build:
      context: ..
      target: celus-nginx
    image: "celus-nginx"
    expose:
      - 80
    ports:
      - 8080:80
    depends_on:
      - web
  redis:
    container_name: "celus-redis"
    image: redis
  celery-worker:
    container_name: "celus-celery-worker"
    build:
      context: ..
      target: celus-django
    image: "celus-django"
    entrypoint: /var/www/celus/entrypoint-celery.py
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ERMS_API_URL=${ERMS_API_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - REDIS_LOCATION=${REDIS_LOCATION}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_WORKER_NORMAL_QUEUES=normal
      - CELERY_WORKER_NORMAL_CONCURRENCY=3
      - CELERY_WORKER_LONG_QUEUES=long
      - CELERY_WORKER_LONG_CONCURRENCY=1
      - CELERY_WORKER_LONG_TIMELIMIT=3600
      - CELERY_WORKER_SUSHI_QUEUES=sushi
      - CELERY_WORKER_SUSHI_CONCURRENCY=2
      - CELERY_WORKER_SUSHI_TIMELIMIT=14400
      - CELERY_WORKER_INTEREST_QUEUES=interest
      - CELERY_WORKER_INTEREST_TIMELIMIT=14400
      - CELERY_WORKER_IMPORT_QUEUES=import
      - CELERY_WORKER_IMPORT_TIMELIMIT=14400
    depends_on:
      - redis
      - postgres
  celery-beat:
    container_name: "celus-celery-beat"
    build:
      context: ..
      target: celus-django
    image: "celus-django"
    entrypoint: /var/www/celus/entrypoint-celery-beat.sh
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ERMS_API_URL=${ERMS_API_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - REDIS_LOCATION=${REDIS_LOCATION}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - redis
      - postgres
