# Generated by Django 3.2.16 on 2023-01-16 08:00

import django.contrib.postgres.fields
from django.db import migrations, models


def fill_platforms(apps, schema_editor):
    ParserDefinition = apps.get_model("nibbler", "ParserDefinition")
    for pd in ParserDefinition.objects.all():
        platforms = pd.definition.get("platforms", [])
        pd.platforms = sorted([e["name"] if isinstance(e, dict) else e for e in platforms])
        pd.save()


class Migration(migrations.Migration):

    dependencies = [('nibbler', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='parserdefinition',
            name='platforms',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Platform's short names from knowledgebase",
                size=None,
            ),
        ),
        migrations.RunPython(fill_platforms, migrations.RunPython.noop),
    ]
