# Generated by Django 2.2.1 on 2019-06-17 15:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('name_cs', models.CharField(max_length=250, null=True)),
                ('desc', models.TextField(blank=True)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('desc_cs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sushi_credentials', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner_level', models.PositiveSmallIntegerField(choices=[(100, 'Normal user'), (200, 'Robot'), (300, 'Organization admin'), (400, 'Consortium staff'), (1000, 'Consortium admin')], default=200, help_text='Level of user who created this record - used to determine who can modify it')),
                ('log_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.LogType')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.OrganizationPlatform')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Title')),
            ],
        ),
    ]
