# Generated by Django 2.2.1 on 2019-06-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimension',
            options={'ordering': ('reporttypetodimension',)},
        ),
        migrations.AlterModelOptions(
            name='reporttypetodimension',
            options={'ordering': ('position',)},
        ),
    ]
