# Generated by Django 2.2.1 on 2019-07-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('core', '0003_datasource'), ('logs', '0003_split_accesslog_source')]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.DataSource',
            ),
        ),
        migrations.AddField(
            model_name='metric',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.DataSource',
            ),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.DataSource',
            ),
        ),
        migrations.AlterField(
            model_name='dimension', name='short_name', field=models.CharField(max_length=100)
        ),
        migrations.AlterField(
            model_name='metric', name='short_name', field=models.CharField(max_length=100)
        ),
        migrations.AlterField(
            model_name='reporttype', name='short_name', field=models.CharField(max_length=100)
        ),
        migrations.AlterUniqueTogether(
            name='dimension', unique_together={('short_name', 'source')}
        ),
        migrations.AlterUniqueTogether(name='metric', unique_together={('short_name', 'source')}),
        migrations.AlterUniqueTogether(
            name='reporttype', unique_together={('short_name', 'source')}
        ),
    ]
