# Generated by Django 2.2.1 on 2019-08-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_metric_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='interest_group',
            field=models.CharField(blank=True, help_text='If given, it marks the metric as representing interest of the specified type', max_length=120, null=True),
        ),
    ]
