# Generated by Django 2.2.4 on 2019-08-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('logs', '0005_metric_active')]

    operations = [
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('short_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('name_cs', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='metric',
            name='interest_group',
            field=models.ForeignKey(
                blank=True,
                help_text='If given, it marks the metric as representing interest of the specified type',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='logs.InterestGroup',
            ),
        ),
    ]
