# Generated by Django 2.2.4 on 2019-08-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_accesslog_import_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importbatch', options={'verbose_name_plural': 'Import batches'},
        ),
    ]
