# Generated by Django 2.2.1 on 2019-08-19 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_even_more_pub_types'),
        ('organizations', '0012_timestamps'),
        ('logs', '0010_verbose_name_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch', name='log', field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='organization',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='organizations.Organization',
            ),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='platform',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Platform'
            ),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='report_type',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='logs.ReportType'
            ),
            preserve_default=False,
        ),
    ]
