# Generated by Django 2.2.4 on 2019-09-02 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_change_data_file_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportInterestMetric',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        help_text='How is the metric called in context of interest',
                        max_length=100,
                    ),
                ),
                (
                    'name_en',
                    models.CharField(
                        blank=True,
                        help_text='How is the metric called in context of interest',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'name_cs',
                    models.CharField(
                        blank=True,
                        help_text='How is the metric called in context of interest',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'metric',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='logs.Metric'
                    ),
                ),
                (
                    'report_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='logs.ReportType'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='reporttype',
            name='interest_metrics',
            field=models.ManyToManyField(through='logs.ReportInterestMetric', to='logs.Metric'),
        ),
    ]
