# Generated by Django 2.2.4 on 2019-09-04 13:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_timestamps'),
        ('logs', '0016_report_interest_metrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ('short_name', 'name')},
        ),
        migrations.CreateModel(
            name='VirtualReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField(blank=True)),
                ('metric_allowed_values', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('base_report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.ReportType')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='DimensionFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_values', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Dimension')),
                ('virtual_report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_filters', to='logs.VirtualReportType')),
            ],
        ),
    ]
