# Generated by Django 2.2.4 on 2019-09-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0018_virtual_report_types_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualreporttype',
            name='primary_dimension',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='logs.Dimension',
            ),
        ),
    ]
