# Generated by Django 2.2.4 on 2019-09-05 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('logs', '0019_virtualreporttype_primary_dimension')]

    operations = [
        migrations.AddField(
            model_name='reportinterestmetric',
            name='interest_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='logs.InterestGroup',
            ),
        ),
        migrations.AddField(
            model_name='reportinterestmetric',
            name='target_metric',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='source_report_interest_metrics',
                to='logs.Metric',
            ),
        ),
    ]
