# Generated by Django 2.2.5 on 2019-09-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('logs', '0021_virtual_report_type_to_report_data_view')]

    operations = [
        migrations.RemoveField(model_name='reportdataview', name='base_report_type'),
        migrations.RemoveField(model_name='reportdataview', name='primary_dimension'),
        migrations.RemoveField(model_name='reportdataview', name='source'),
        migrations.DeleteModel(name='DimensionFilter'),
        migrations.DeleteModel(name='ReportDataView'),
    ]
