# Generated by Django 2.2.5 on 2019-10-23 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0024_no_reportinterestmetric_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinterestmetric',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportinterestmetric',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
