# Generated by Django 2.2.5 on 2019-11-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0026_interest_group_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='interest_timestamp',
            field=models.DateTimeField(
                blank=True, help_text='When was interest procesed for this batch', null=True
            ),
        ),
    ]
