# Generated by Django 2.2.5 on 2019-11-07 10:05

from django.db import migrations
from django.utils.datetime_safe import datetime
from django.utils.timezone import utc


def add_interest_timestamp_where_interest_processed(apps, schema_editor):
    ImportBatch = apps.get_model('logs', 'ImportBatch')
    ImportBatch.objects.filter(interest_processed=True, interest_timestamp__isnull=True).\
        update(interest_timestamp=datetime(2018, 1, 1, 0, 0, 0, tzinfo=utc))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0028_reporttype_superseeded_by'),
    ]

    operations = [
        migrations.RunPython(add_interest_timestamp_where_interest_processed, noop),
        migrations.RemoveField(
            model_name='importbatch',
            name='interest_processed',
        ),
    ]
