# Generated by Django 2.2.5 on 2019-11-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('logs', '0029_remove_importbatch_interest_processed')]

    operations = [
        migrations.AddField(
            model_name='manualdataupload',
            name='owner_level',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (100, 'Normal user'),
                    (200, 'Robot'),
                    (300, 'Organization admin'),
                    (400, 'Consortium staff'),
                    (1000, 'Consortium admin'),
                ],
                default=200,
                help_text='Level of user who created this record - used to determine who can modify it',
            ),
        )
    ]
