# Generated by Django 2.2.17 on 2021-03-04 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0034_importbatch_materialization_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='materialization_date',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text='All data materialized before this data will be recomputed - can be used to force recomputation',
            ),
        ),
    ]
