# Generated by Django 3.0.10 on 2020-11-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_datasource_set_null'),
        ('logs', '0035_reporttype_default_platform_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.DataSource',
            ),
        ),
        migrations.AlterField(
            model_name='metric',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.DataSource',
            ),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.DataSource',
            ),
        ),
    ]
