# Generated by Django 3.1.6 on 2021-03-04 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('logs', '0037_jsonfield')]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='materialization_date',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text='All data materialized before this data will be recomputed - can be used to force recomputation',
            ),
        )
    ]
