# Generated by Django 3.1.3 on 2021-01-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0038_flexiblereport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(name='dimension', unique_together=set(),),
        migrations.AddConstraint(
            model_name='dimension',
            constraint=models.UniqueConstraint(
                fields=('short_name', 'source'), name='short_name_source_not_null'
            ),
        ),
        migrations.AddConstraint(
            model_name='dimension',
            constraint=models.UniqueConstraint(
                condition=models.Q(source=None),
                fields=('short_name',),
                name='short_name_source_null',
            ),
        ),
    ]
