# Generated by Django 3.1.6 on 2021-03-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0040_reporttype_approx_record_count'),
        ('logs', '0038_reporttype_materialization_date'),
    ]

    operations = []
