# Generated by Django 3.1.6 on 2021-03-29 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0041_merge_20210327_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexiblereport',
            name='last_updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='owned_flexible_reports',
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
