# Generated by Django 3.2.9 on 2021-11-16 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import Exists, OuterRef


def create_import_batch_sync_logs(apps, schema_editor):
    ImportBatch = apps.get_model('logs', 'ImportBatch')
    ImportBatchSyncLog = apps.get_model('logs', 'ImportBatchSyncLog')
    related_sync_log = ImportBatchSyncLog.objects.filter(import_batch_id=OuterRef('pk'))
    logs_to_add = []
    for ib in ImportBatch.objects.exclude(Exists(related_sync_log)):
        logs_to_add.append(ImportBatchSyncLog(import_batch_id=ib.pk))
    ImportBatchSyncLog.objects.bulk_create(logs_to_add)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0047_importbatch_last_updated_clickhoused'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatchSyncLog',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                (
                    'import_batch_id',
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    'state',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'No change'),
                            (1, 'Sync'),
                            (2, 'Delete'),
                            (3, 'Sync interest'),
                        ],
                        default=0,
                    ),
                ),
                (
                    'last_updated_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.RunPython(create_import_batch_sync_logs, migrations.RunPython.noop),
    ]
