# Generated by Django 3.2.11 on 2022-01-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0049_mdu_many_importbatches'),
    ]

    operations = [
        migrations.RemoveField(model_name='manualdataupload', name='import_batch',),
        migrations.AddField(
            model_name='importbatch', name='date', field=models.DateField(null=True),
        ),
    ]
