# Generated by Django 3.2.10 on 2022-02-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0051_split_import_batches'),
    ]

    operations = [
        migrations.RemoveField(model_name='importbatch', name='system_created',),
    ]
