# Generated by Django 3.2.12 on 2022-02-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0054_fill_importbatch_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(
                fields=['platform', 'organization', 'report_type'],
                name='logs_access_platfor_cdb3c4_idx',
            ),
        ),
    ]
