# Generated by Django 3.2.12 on 2022-02-23 09:12

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0055_accesslog_logs_access_platfor_cdb3c4_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='importbatch',
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=['date'], name='logs_import_date_269c60_brin'
            ),
        ),
    ]
