# Generated by Django 3.2.12 on 2022-02-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0057_rename_extra_manualdataupload_preflight'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdataupload',
            name='error',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
