# Generated by Django 3.2.12 on 2022-03-16 09:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('logs', '0059_manualdataupload_state')]

    operations = [
        migrations.CreateModel(
            name='ControlledMetric',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'metric',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='logs.metric'
                    ),
                ),
                (
                    'report_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='logs.reporttype'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='reporttype',
            name='controlled_metrics',
            field=models.ManyToManyField(
                related_name='controlled', through='logs.ControlledMetric', to='logs.Metric'
            ),
        ),
        migrations.AddConstraint(
            model_name='controlledmetric',
            constraint=models.UniqueConstraint(
                fields=('metric_id', 'report_type_id'),
                name='controlled_report_type_and_metric_unique',
            ),
        ),
    ]
