# Generated by Django 3.2.12 on 2022-03-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0060_controlled_metrics'),
    ]

    operations = [
        migrations.RemoveField(model_name='manualdataupload', name='is_processed',),
    ]
