# Generated by Django 3.2.12 on 2022-03-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0057_verbose_names'),
        ('logs', '0061_remove_manualdataupload_is_processed'),
    ]

    operations = []
