# Generated by Django 3.2.12 on 2022-03-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('logs', '0063_alter_reportinterestmetric_interest_group')]

    operations = [
        migrations.AddField(
            model_name='manualdataupload',
            name='error_details',
            field=models.JSONField(blank=True, null=True),
        )
    ]
