# Generated by Django 3.2.12 on 2022-04-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0064_manualdataupload_error_details'),
    ]

    operations = [migrations.RemoveField(model_name='dimension', name='type')]
