# Generated by Django 3.2.13 on 2022-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0066_lastaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatchsynclog',
            name='state',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'No change'),
                    (1, 'Sync'),
                    (2, 'Delete'),
                    (3, 'Sync interest'),
                    (4, 'Resync'),
                ],
                default=0,
            ),
        ),
    ]
