# Generated by Django 3.2.13 on 2022-06-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0067_alter_importbatchsynclog_state'),
        ('logs', '0068_file_checksums'),
    ]

    operations = []
