# Generated by Django 3.2.15 on 2022-08-09 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('logs', '0071_mdu_import_batch_ordering')]

    operations = [
        migrations.AddField(
            model_name='manualdataupload',
            name='use_nibbler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manualdataupload',
            name='report_type',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.reporttype'
            ),
        ),
        migrations.AddConstraint(
            model_name='manualdataupload',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('use_nibbler', False), ('report_type__isnull', True), _negated=True
                ),
                name='non-nibbler-needs-report-type',
            ),
        ),
    ]
