# Generated by Django 3.2.18 on 2023-04-03 14:04
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0074_mdu_method"),
        ("publications", "0037_add_ir_m1_interest_to_all_platforms"),
    ]

    # there was a migration here which created the multimedia interest group
    # but now that we have the interest 2.0, we don't need it anymore and it
    # even caused problems in tests where it leads to unexpected interest groups
    # and metrics appearing in the database.
    operations = []
