# Generated by Django 3.2.19 on 2023-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('logs', '0076_deduplicate_metrics'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dimension',
            name='short_name_source_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='dimension',
            name='short_name_source_null',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='source',
        ),
        migrations.AddConstraint(
            model_name='dimension',
            constraint=models.UniqueConstraint(fields=('short_name',), name='short_name_unique'),
        ),
    ]
