# Generated by Django 3.2.19 on 2023-07-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0077_remove_source_from_dimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationplatform',
            name='sushi_credentials',
        ),
    ]
