# Generated by Django 3.2.20 on 2023-09-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_alter_userorganization_unique_together'),
        ('publications', '0038_issn_eissn_index'),
        ('logs', '0079_alter_importbatch_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationplatform',
            unique_together={('organization', 'platform')},
        ),
    ]
