# Generated by Django 4.2.11 on 2024-03-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0081_mdu_extra_and_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="manual_empty",
            field=models.BooleanField(
                default=False, help_text="If the batch was created manually by the user as empty"
            ),
        ),
    ]
