# Generated by Django 4.2.11 on 2024-03-18 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0041_item"),
        ("logs", "0083_alter_importbatchsynclog_last_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslog",
            name="item",
            field=models.ForeignKey(
                help_text="Item for which this log was created",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="publications.item",
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="dim8",
            field=models.IntegerField(blank=True, help_text="Value in dimension #8", null=True),
        ),
        migrations.AddField(
            model_name="reportmaterializationspec",
            name="keep_dim8",
            field=models.BooleanField(default=True),
        ),
    ]
