# Generated by Django 4.2.15 on 2024-08-29 08:07

from django.db import migrations, models


def set_denial_not_available(apps, schema_editor):
    InterestGroup = apps.get_model("logs", "InterestGroup")
    InterestGroup.objects.filter(short_name__icontains="denial").update(implies_availability=False)


class Migration(migrations.Migration):
    dependencies = [("logs", "0084_accesslog_item_and_dim8")]

    operations = [
        migrations.AddField(
            model_name="interestgroup",
            name="implies_availability",
            field=models.BooleanField(
                default=True,
                help_text="Does existence of this kind of interest imply that the resource is "
                "available? Should be set to False for denials.",
            ),
        ),
        migrations.RunPython(set_denial_not_available, migrations.RunPython.noop),
    ]
