# Generated by Django 4.2.15 on 2024-10-14 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("logs", "0086_flexiblereport_created_by_and_more")]

    operations = [
        migrations.RenameField(
            model_name="reporttype", old_name="superseeded_by", new_name="superseded_by"
        ),
        migrations.AlterField(
            model_name="reporttype",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="logs.reporttype",
            ),
        ),
        migrations.AddField(
            model_name="reportmaterializationspec",
            name="keep_item",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reporttype",
            name="default_platform_interest",
            field=models.BooleanField(
                default=False,
                help_text="Should this report type be automatically connected to new platforms?",
            ),
        ),
        migrations.AlterField(
            model_name="reporttype",
            name="materialization_spec",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logs.reportmaterializationspec",
            ),
        ),
    ]
