# Generated by Django 4.2.19 on 2025-02-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("logs", "0087_remove_reporttype_superseeded_by_and_more")]

    operations = [
        migrations.AlterField(model_name="importbatch", name="date", field=models.DateField())
    ]
