# Generated by Django 4.2.19 on 2025-04-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("logs", "0088_alter_importbatch_date")]

    operations = [
        migrations.AddField(
            model_name="flexiblereport",
            name="description",
            field=models.TextField(blank=True, default=""),
        )
    ]
