# Generated by Django 4.2.19 on 2025-04-19 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logs", "0089_flexiblereport_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlexibleReportUserEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("XLSX", "XLSX"),
                            ("XLSX_NO_CHARTS", "XLSX without charts"),
                            ("ZIP_CSV", "CSV files inside ZIP archive"),
                        ],
                        default="XLSX",
                        max_length=16,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("M", "Monthly"),
                            ("Q", "Quarterly"),
                            ("H", "Half-yearly"),
                            ("Y", "Yearly"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "fiscal_period",
                    models.BooleanField(
                        default=False,
                        help_text="If True, the frequency is interpreted relative to the fiscal "
                        "year",
                    ),
                ),
                ("number_of_periods", models.PositiveSmallIntegerField(default=1)),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "flexible_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logs.flexiblereport"
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flexible_report_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
