# Generated by Django 4.2.19 on 2025-04-14 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_interest_group_metric(apps, schema_editor):
    InterestGroup = apps.get_model("logs", "InterestGroup")
    Metric = apps.get_model("logs", "Metric")
    for interest_group in InterestGroup.objects.all():
        metric, _ = Metric.objects.get_or_create(
            short_name=interest_group.short_name,
            defaults={"name_en": interest_group.name_en, "name_cs": interest_group.name_cs},
        )
        interest_group.metric = metric
        interest_group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0026_userorganization_send_harvest_reports"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logs", "0090_flexiblereportuseremail"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimensionFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("values", models.JSONField(default=list)),
                ("negated", models.BooleanField(default=False)),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_filters",
                        to="logs.dimension",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterestConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("organization",)},
        ),
        migrations.CreateModel(
            name="InterestProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("short_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=250)),
                ("desc", models.TextField(blank=True)),
            ],
            options={"ordering": ("short_name", "name")},
        ),
        migrations.RemoveField(model_name="reportinterestmetric", name="target_metric"),
        migrations.RemoveField(model_name="reporttype", name="default_platform_interest"),
        migrations.AddField(
            model_name="importbatch",
            name="interest_ib",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the import batch that includes interest data for this batch - "
                "can be either the same batch or a superseding one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseded_interest_ibs",
                to="logs.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="interestgroup",
            name="metric",
            field=models.OneToOneField(
                blank=True,
                help_text="Metric which represents this kind of interest",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interest_group",
                to="logs.metric",
            ),
        ),
        migrations.CreateModel(
            name="ReportInterestMetricFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rim_filters",
                        to="logs.dimensionfilter",
                    ),
                ),
                (
                    "report_interest_metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logs.reportinterestmetric"
                    ),
                ),
            ],
            options={"unique_together": {("report_interest_metric", "filter")}},
        ),
        migrations.CreateModel(
            name="InterestFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logs.dimensionfilter"
                    ),
                ),
                (
                    "interest_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logs.interestconfig"
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="interestconfig",
            name="interest_filters",
            field=models.ManyToManyField(through="logs.InterestFilter", to="logs.dimensionfilter"),
        ),
        migrations.AddField(
            model_name="interestconfig",
            name="interest_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interest_config",
                to="logs.interestprofile",
            ),
        ),
        migrations.AddField(
            model_name="interestconfig",
            name="last_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interestconfig",
            name="organization",
            field=models.OneToOneField(
                blank=True,
                help_text="If not set, the config will be the default one",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interest_config",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="reportinterestmetric",
            name="filters",
            field=models.ManyToManyField(
                through="logs.ReportInterestMetricFilter", to="logs.dimensionfilter"
            ),
        ),
        migrations.AddField(
            model_name="reportinterestmetric",
            name="interest_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="If given, this RIM will be taken into account only for organizations "
                "which have this profile active. If null, will be used regardless of profile.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logs.interestprofile",
            ),
        ),
        migrations.CreateModel(
            name="InterestDimensionValueMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "default_value",
                    models.CharField(
                        help_text="Used when value is not found in mapping", max_length=250
                    ),
                ),
                (
                    "mapping",
                    models.JSONField(
                        default=dict,
                        help_text="Mapping between interest dimension value and source dimension "
                        "values: str->[str]",
                    ),
                ),
                (
                    "interest_rtdim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_value_mappings",
                        to="logs.reporttypetodimension",
                    ),
                ),
                (
                    "source_rtdim",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, represents default for this interest dimension; "
                        "otherwise report type specific dimension",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logs.reporttypetodimension",
                    ),
                ),
            ],
            options={"unique_together": {("interest_rtdim", "source_rtdim")}},
        ),
        migrations.AddConstraint(
            model_name="interestconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization", None)),
                fields=("organization",),
                name="only_one_default_interest_config",
            ),
        ),
        migrations.RunPython(migrate_interest_group_metric, migrations.RunPython.noop),
    ]
