# Generated by Django 4.2.19 on 2025-04-14 12:18

import django.db.models.deletion
from django.db import migrations, models

# NOTE: this migration cannot be run in the same migration as the previous one
# because the change of nullability of the metric field is not allowed in the same
# migration as the field is created.


class Migration(migrations.Migration):
    dependencies = [("logs", "0091_dimensionfilter_interestconfig_interestprofile_and_more")]

    operations = [
        migrations.AlterField(
            model_name="interestgroup",
            name="metric",
            field=models.OneToOneField(
                help_text="Metric which represents this kind of interest",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interest_group",
                to="logs.metric",
            ),
        )
    ]
