# Generated by Django 4.2.23 on 2025-07-04 08:07

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("logs", "0092_alter_interestgroup_metric")]

    operations = [
        migrations.RemoveConstraint(
            model_name="interestconfig", name="only_one_default_interest_config"
        ),
        migrations.AddConstraint(
            model_name="interestconfig",
            constraint=models.UniqueConstraint(
                django.db.models.functions.comparison.Coalesce("organization", models.Value(0)),
                name="only_one_default_interest_config",
            ),
        ),
    ]
