# Generated by Django 4.2.23 on 2025-07-24 05:47

from django.db import migrations, models


# we need to migrate the IR51 report type to use items
def migrate_ir51_to_use_items(apps, schema_editor):
    ReportType = apps.get_model("logs", "ReportType")
    ReportType.objects.filter(short_name="IR51").update(uses_items=True)


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0093_remove_interestconfig_only_one_default_interest_config_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="reporttype", name="uses_items", field=models.BooleanField(default=False)
        ),
        migrations.RunPython(migrate_ir51_to_use_items, reverse_code=migrations.RunPython.noop),
    ]
