# Generated by Django 4.2.23 on 2025-08-07 06:17

import itertools
from time import monotonic

from django.conf import settings
from django.db import migrations, models
from hcube.api.models.aggregation import Count as HCount

from logs.cubes import AccessLogCube, ch_backend


def update_record_count(apps, schema_editor):
    ImportBatch = apps.get_model("logs", "ImportBatch")
    AccessLog = apps.get_model("logs", "AccessLog")
    ReportType = apps.get_model("logs", "ReportType")
    start = monotonic()
    if settings.CLICKHOUSE_QUERY_ACTIVE:
        # clickhouse is much faster in this and because it does not contain materialized
        # report type data, we can use a simpler filtering method - just exclude interest
        interest_rt = ReportType.objects.filter(short_name="interest", source__isnull=True).first()
        if interest_rt:
            query = (
                AccessLogCube.query()
                .filter(report_type_id__not_in=[interest_rt.id])
                .group_by("import_batch_id")
                .aggregate(rc=HCount())
            )
            ib_to_count = {rec.import_batch_id: rec.rc for rec in ch_backend.get_records(query)}
            # let's do it in chunks of 1000
            records = iter(ib_to_count.keys())
            updated = 0
            while batch := list(itertools.islice(records, 1000)):
                to_save = []
                for ib in ImportBatch.objects.filter(id__in=batch).only("id", "record_count"):
                    ib.record_count = ib_to_count.get(ib.id, 0)
                    to_save.append(ib)
                    updated += 1
                ImportBatch.objects.bulk_update(to_save, ["record_count"])
            print(
                f"Updated {updated} import batches using clickhouse in "
                f"{monotonic() - start:.2f} seconds"
            )
            return

    # if clickhouse cannot be used, use this default method (very slow)
    # BTW, I tried doing this in one query using Subquery, but it was even slower :/
    updated = 0
    for batch in ImportBatch.objects.all().only("id", "record_count"):
        al_count = AccessLog.objects.filter(
            import_batch=batch, report_type_id=batch.report_type_id
        ).count()
        if al_count:
            batch.record_count = al_count
            batch.save(update_fields=["record_count"])
            updated += 1
    print(f"Updated {updated} import batches in {monotonic() - start:.2f} seconds")


class Migration(migrations.Migration):
    dependencies = [("logs", "0094_reporttype_uses_items")]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="record_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of associated accesslog records without artificial ones "
                "(no interest, no materialized report types)",
            ),
        ),
        migrations.RunPython(update_record_count, reverse_code=migrations.RunPython.noop),
    ]
