# Generated by Django 4.2.23 on 2025-08-27 11:26

from django.db import migrations


def migrate_primary_dimension(model, from_value, to_value):
    """
    Migrate the primary dimension of a report from one value to another.
    """
    for fr in model.objects.filter(report_config__contains={"primary_dimension": from_value}):
        if any(
            fltr.get("dimension") == "report_type" and fltr.get("values") == ["IR_M1"]
            for fltr in fr.report_config.get("filters", [])
        ):
            fr.report_config["primary_dimension"] = to_value
        fr.save()


def migrate_irm1_titles_to_items(apps, schema_editor):
    FlexibleReport = apps.get_model("logs", "FlexibleReport")
    # any report using IR_M1 and showing titles should be converted to show items
    migrate_primary_dimension(FlexibleReport, "title", "item")


def migrate_irm1_items_to_titles(apps, schema_editor):
    FlexibleReport = apps.get_model("logs", "FlexibleReport")
    # any report using IR_M1 and showing items should be converted to show titles
    migrate_primary_dimension(FlexibleReport, "item", "title")


class Migration(migrations.Migration):
    dependencies = [("logs", "0095_importbatch_record_count")]

    operations = [migrations.RunPython(migrate_irm1_titles_to_items, migrate_irm1_items_to_titles)]
