# Generated by Django 4.2.23 on 2025-09-05 11:36

# Clickhouse 25.7 introduced lightweight updates, which are much faster than the old way
# They also allow very fast deletes of data, which is important for us.
# https://clickhouse.com/blog/clickhouse-release-25-07#lightweight-updates

# HCube already supports them, but there is a clickhouse-specific migration necessary to make
# them work. Therefore we implement it here as a data migration, because we have no mechanism
# to run clickhouse-specific migrations (unless the change is supported by hcube, which is not
# the case for this one).

# Small note about performance:
# On my local machine, when using copy of K1, deleting of individual import batches from
# Clickhouse normally takes 0.6 seconds. With lightweight updates, it takes 0.01 seconds.
# This makes IR_M1 reimport much faster, as it potentially involves a lot of deletions.

from django.conf import settings
from django.db import migrations

from logs.cubes import AccessLogCube, ch_backend


def enable_lightweight_updates(apps, schema_editor):
    if settings.CLICKHOUSE_SYNC_ACTIVE:
        with ch_backend.pool.get_client() as client:
            table_name = ch_backend.cube_to_table_name(AccessLogCube)
            client.execute(
                f"ALTER TABLE {table_name} MODIFY SETTING "
                "enable_block_number_column=1, enable_block_offset_column=1"
            )
            print(
                "Enabled lightweight updates for AccessLogCube "
                "(enable_block_number_column=1, enable_block_offset_column=1)"
            )


class Migration(migrations.Migration):
    dependencies = [("logs", "0096_flexiblereports_for_irm1_titles_to_items")]

    operations = [migrations.RunPython(enable_lightweight_updates, migrations.RunPython.noop)]
