# Generated by Django 4.2.23 on 2025-08-05 08:31

from django.db import migrations, models


def update_uses_titles_and_uses_items(apps, schema_editor):
    ReportType = apps.get_model("logs", "ReportType")
    # Disable uses_titles for PR based reports and IR_M1
    ReportType.objects.filter(short_name__in=["PR", "PR1", "PR51", "IR_M1"]).update(
        uses_titles=False
    )
    # Note that IR_M1 is still using title and would be dealt with in upcoming migration


class Migration(migrations.Migration):
    dependencies = [("logs", "0097_clickhouse_enable_lightweight_updates")]

    operations = [
        migrations.AddField(
            model_name="reporttype", name="uses_titles", field=models.BooleanField(default=True)
        ),
        migrations.RunPython(
            update_uses_titles_and_uses_items, reverse_code=migrations.RunPython.noop
        ),
    ]
