# Generated by Django 4.2.24 on 2025-10-07 12:24

from django.db import migrations
from django.db.utils import settings


def localize_normal_access_method_as_regular(apps, schema_editor):
    """
    Add the `Regular` translation for the `Access_Method` dimension with text value `Normal`.
    The text itself remains the same - it is `Normal` before and after the migration.
    """
    DimensionText = apps.get_model("logs", "DimensionText")
    langs = [lng[0] for lng in settings.LANGUAGES]
    attrs = {f"text_local_{lang}": "Regular" for lang in langs}
    DimensionText.objects.filter(dimension__short_name="Access_Method", text="Normal").update(
        **attrs
    )


def reverse_localize_normal_access_method_as_regular(apps, schema_editor):
    """
    Remove the `Regular` translation for the `Access_Method` dimension with text value `Normal`.
    When the translation is empty, the default value `Normal` from `text` field is used.
    """
    DimensionText = apps.get_model("logs", "DimensionText")
    langs = [lng[0] for lng in settings.LANGUAGES]
    attrs = {f"text_local_{lang}": "" for lang in langs}
    DimensionText.objects.filter(dimension__short_name="Access_Method", text="Normal").update(
        **attrs
    )


class Migration(migrations.Migration):
    dependencies = [("logs", "0098_reporttype_uses_titles")]

    operations = [
        migrations.RunPython(
            localize_normal_access_method_as_regular,
            reverse_localize_normal_access_method_as_regular,
        )
    ]
