# Generated by Django 5.2.7 on 2025-11-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("logs", "0099_localize_normal_access_method_as_regular")]

    operations = [
        migrations.AlterField(
            model_name="reporttype",
            name="interest_metrics",
            field=models.ManyToManyField(
                through="logs.ReportInterestMetric",
                through_fields=("report_type", "metric"),
                to="logs.metric",
            ),
        )
    ]
