# Generated by Django 4.2.25 on 2025-11-18 13:09

import django
from django.db import migrations, models


def guess_used_parser(apps, schema_editor):
    ParserDefinition = apps.get_model("nibbler", "ParserDefinition")
    ManualDataUpload = apps.get_model("logs", "ManualDataUpload")

    pds = [(e.report_type_short_name, e.short_name) for e in ParserDefinition.objects.all()]
    for mdu in ManualDataUpload.objects.all():
        match mdu.method:
            case "raw":
                if mdu.report_type:
                    rt_short = mdu.report_type.short_name
                    # Try to get parsers name for such report type
                    names = [e[1] for e in pds if e[0] == rt_short]
                else:
                    rt_short = "unknown"
                    names = []
                names = ["unknown"] if not names else names
                mdu.nibbler_parser_names = [
                    f"dynamic.non_counter.{rt_short}.{name}" for name in names
                ]
            case "celus":
                rt_short = mdu.report_type.short_name if mdu.report_type else "unknown"
                mdu.nibbler_parser_names = [f"dynamic.non_counter.{rt_short}.Tabular"]
            case "counter":
                if mdu.report_type:
                    rt_short = mdu.report_type.counterreporttype.code
                    counter_version = mdu.report_type.counterreporttype.counter_version
                else:
                    rt_short = "unknown"
                    counter_version = ""
                format = "Json" if mdu.data_file.name.endswith(".json") else "Tabular"
                mdu.nibbler_parser_names = [f"static.counter{counter_version}.{rt_short}.{format}"]
        mdu.save()


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0100_alter_reporttype_interest_metrics"),
        ("nibbler", "0002_parserdefinition_platforms"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualdataupload",
            name="nibbler_parser_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                help_text="Parser names used to extract data",
                size=None,
            ),
        ),
        migrations.RunPython(guess_used_parser, reverse_code=migrations.RunPython.noop),
    ]
