# Generated by Django 4.2.24 on 2025-09-26 11:56

import django.db.models.deletion
import django.db.models.functions.comparison
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logs", "0098_reporttype_uses_titles"),
        ("organizations", "0028_alter_userorganization_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLogExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("ch_database", models.CharField(blank=True, max_length=128)),
                ("ch_password", models.CharField(blank=True, max_length=128)),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        blank=True,
                        help_text="When empty, it represents export for the whole consortium",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessLogExportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "export",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ch_export.accesslogexport"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessLogExportTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=128)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("started", models.DateTimeField(blank=True, null=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ch_export.accesslogexportbatch",
                    ),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logs.reporttype"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="accesslogexporttask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("task_id", ""), _negated=True),
                fields=("task_id",),
                name="unique_task_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesslogexport",
            constraint=models.UniqueConstraint(
                django.db.models.functions.comparison.Coalesce("organization", models.Value(0)),
                name="only_one_consortium_export",
            ),
        ),
    ]
