# Generated by Django 5.2.7 on 2025-11-20 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("ch_export", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="accesslogexportbatch",
            options={"ordering": ["-created"], "verbose_name_plural": "Access log export batches"},
        )
    ]
