# Generated by Django 2.2.1 on 2019-07-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190701_0642'),
        ('organizations', '0003_non_unique_ico'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defined_organizations', to='core.DataSource'),
        ),
    ]
