# Generated by Django 2.2.1 on 2019-08-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('organizations', '0007_sushicredentials')]

    operations = [
        migrations.AddField(
            model_name='sushicredentials', name='enabled', field=models.BooleanField(default=True)
        )
    ]
