# Generated by Django 2.2.1 on 2019-08-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('organizations', '0009_sushi_credentials_tuning')]

    operations = [migrations.DeleteModel(name='SushiCredentials')]
