# Generated by Django 2.2.4 on 2019-08-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blank_ext_id'),
        ('organizations', '0010_delete_sushicredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganization',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DataSource'),
        ),
    ]
