# Generated by Django 2.2.9 on 2020-01-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20191113_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ico',
            field=models.PositiveIntegerField(
                blank=True, help_text='Business registration number', null=True
            ),
        ),
    ]
