# Generated by Django 3.2.12 on 2022-03-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_organization_unique_shortname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization', options={'ordering': ('name',), 'verbose_name': 'Organization'},
        ),
    ]
