# Generated by Django 3.2.18 on 2023-04-11 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("organizations", "0022_organization_raw_enabled")]

    operations = [
        migrations.AlterModelOptions(name="organizationaltname", options={"ordering": ["name"]})
    ]
