# Generated by Django 3.2.19 on 2023-05-16 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0023_alter_organizationaltname_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userorganization", unique_together={("user", "organization")}
        )
    ]
