# Generated by Django 4.2.19 on 2025-03-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organizations", "0025_organization_country_organization_isni_and_more")]

    operations = [
        migrations.AddField(
            model_name="userorganization",
            name="send_harvest_reports",
            field=models.BooleanField(
                default=False, help_text="If checked harvest report per oganization will be sent"
            ),
        )
    ]
