# Generated by Django 4.2.23 on 2025-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organizations", "0026_userorganization_send_harvest_reports")]

    operations = [
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source__isnull", True)),
                fields=("short_name_en",),
                name="organization_unique_global_shortname-short_name_en",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source__isnull", True)),
                fields=("short_name_cs",),
                name="organization_unique_global_shortname-short_name_cs",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ext_id__isnull", True)),
                fields=("short_name_en", "source"),
                name="organization_unique_short_name_source-short_name_en",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ext_id__isnull", True)),
                fields=("short_name_cs", "source"),
                name="organization_unique_short_name_source-short_name_cs",
            ),
        ),
    ]
