# Generated by Django 4.2.23 on 2025-08-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0027_organization_organization_unique_global_shortname_short_name_en_and_more",
        )
    ]

    operations = [
        migrations.AlterUniqueTogether(name="userorganization", unique_together=set()),
        migrations.AddField(
            model_name="userorganization",
            name="can_impersonate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="userorganization",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"), name="unique_user_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="userorganization",
            constraint=models.CheckConstraint(
                check=models.Q(("is_admin", False), ("can_impersonate", True), _negated=True),
                name="user_org_non_admins_cant_impersonate",
            ),
        ),
    ]
